### ISSUE TITLE
Bad link in Challenge 80 page

### ISSUE THREAD

**Issue by fturmel** [CodingTrain/thecodingtrain.com#1004]
In [challenge 80](https://thecodingtrain.com/challenges/80-voice-chatbot-with-p5speech), I found a legacy link in the `videos` tab that points to `/learning/programming-with-text`.

<img width="1099" alt="Screenshot 2023-04-15 at 1 18 17 PM" src="https://user-images.githubusercontent.com/4009209/232242204-b001186a-fab6-4ebc-8632-9f7b8d0bf7ec.png">

Is this a missing track? Do we have a replacement URL or should this be removed?

**Comment by dipamsen** [comment]
The programming with text track is not ported to the website, so the link should point to the YouTube playlist: https://www.youtube.com/playlist?list=PLRqwX-V7Uu6YrbSJBg32eTzUU50E2B8Ch

**Comment by fturmel** [comment]
Perfect, thank you. I'll replace the link with the YouTube playlist in an upcoming PR with other content fixes.
