### ISSUE TITLE
Missing `relatedChallenges`

### ISSUE THREAD

**Issue by fturmel** [CodingTrain/thecodingtrain.com#1005]
If someone wants to complete this data entry task, I found only 11 challenges on the site that didn't have related challenges.

- [x] 148-gift-wrapping
- [x] 157-zoom-annotations
- [x] 164-slitscan
- [x] 166-image-to-ascii
- [x] 167-prime-spiral
- [x] 170-monty-hall-problem
- [x] 171-wave-function-collapse
- [x] 172-directional-boring
- [x] 56-attraction-and-repulsion-forces
- [x] 67-pong
- [x] c3-hilbert-curve

**Comment by kfahn22** [comment]
I have started working on this.

**Comment by fturmel** [comment]
Re-opening this, `c3-hilbert-curve` is left

**Comment by shiffman** [comment]
#1015 covers `c3-hilbert-curve` so I believe this can be closed?

**Comment by fturmel** [comment]
Yes, we can close this
