### ISSUE TITLE
Add Related Challenges to Track Videos

### ISSUE THREAD

**Issue by dipamsen** [CodingTrain/thecodingtrain.com#1014]
Add `relatedChallenges` field to non-challenge videos (videos in tracks)

- [ ] Nature of Code
- [ ] p5.js
- [ ] other tracks

(The `relatedChallenges` field is not required for all videos, it should be only added to videos wherever applicable.)

> **Related Challenges:**
>
> This property let's us link challenges to a specific video in any way you see fit. It's an array of slugs, which should match the path slug of a challenge (relative to content/videos/challenges) to correctly reference it.
> 
> If it's not defined or is left empty, then no challenge panel is shown in the corresponding video page. Multiple slugs can be added, but randomly two will be shown on the page.

![related challenges preview](https://user-images.githubusercontent.com/59444569/233803516-eba336fe-6de2-4a70-99ef-0e8a0b13ca93.png)

**Comment by shiffman** [comment]
I think @kfahn22 did a lot of work adding many related challenges around the site, shall we close this issue now?
