### ISSUE TITLE
Track topics and languages

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#1039]
I need to investigate this more but I noticed that several of the side tracks do not show topics or languages. I believe these are meant to be compiled from the topics and languages of the videos that are contained within the tracks? I see the following three scenarios:

* all topics/languages compiled
* only topics/languages from the first video in the track
* no topics/languages listed

I'm not sure what causes one of the above scenarios to occur? Does anyone have an idea?

Example:
![Screen Shot 2023-05-03 at 2 50 54 PM](https://user-images.githubusercontent.com/191758/236015347-a7eb9fdb-05ab-4924-83e6-e30073daafc4.png)

**Comment by shiffman** [comment]
@fdoflorenzano can you confirm that the intended behavior is to compile topics/languages from the videos rather than maintain a separate list of topics/languages for each track?

**Comment by dipamsen** [comment]
Thats weird. I'm pretty sure they were there earlier

**Comment by fturmel** [comment]
One pattern I'm noticing is it affects the tracks made up only of challenge videos.

**Comment by dipamsen** [comment]
@fturmel You might have found this already, but I think this is the issue - 
https://github.com/CodingTrain/thecodingtrain.com/blob/f2923999ad2b216bc8a65387a6479067e878c96d/gatsby-node.js#L270-L274
challenges are `Challenge`s, not `Video`s, so they are not getting pulled here

**Comment by fturmel** [comment]
> @fturmel You might have found this already, but I think this is the issue -
> 
> https://github.com/CodingTrain/thecodingtrain.com/blob/f2923999ad2b216bc8a65387a6479067e878c96d/gatsby-node.js#L270-L274
> 
> 
> challenges are `Challenge`s, not `Video`s, so they are not getting pulled here

That's it, figured it out roughly at the same time as you did. PR incoming.
