### ISSUE TITLE
Pixel Array Video

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#1050]
The pixel array video needs a spot on the website (as it's referenced in the Nature of Code book). 

https://youtu.be/nMUMZ5YRxHI

What makes the most sense? Maybe the "p5 tips and tricks" side track?

https://thecodingtrain.com/tracks/p5-tips-and-tricks

**Comment by kfahn22** [comment]
Yes that I think that makes sense.  I can add it.

**Comment by shiffman** [comment]
Thank you @kfahn22! Closing with #1052!
