### ISSUE TITLE
Missing thumbnail images for (older) showcase contributions

### ISSUE THREAD

**Issue by fturmel** [CodingTrain/thecodingtrain.com#1057]
99 out of 1398 (~14%) showcase contributions do not have an accompanying image. Just dumping this here in case someone wants to take screenshots and help close this gap.

It's not breaking the site, but we are displaying a placeholder that doesn't give information about the featured work so it would be a nice low priority improvement. Low-hanging fruit for first-time GitHub contributions maybe?

<img width="511" alt="Screenshot 2023-05-15 at 1 20 57 PM" src="https://github.com/CodingTrain/thecodingtrain.com/assets/4009209/02f52f93-f995-4f42-b3f9-b1efee1e9790">

Reminder on the **image specs** (from the [contribution guide](https://thecodingtrain.com/guides/passenger-showcase-guide#adding-a-preview-image)):
> While any aspect ratio is fine (the site will resize and crop as necessary), the images will be displayed at 16:9 aspect ratio. We suggest you upload a "landscape" image. The file format should be JPG or PNG, with a maximum width of 800px and file size of 500 kb. Name your thumbnail image with the same filename as your showcase submission (contribution1.png, contribution2.jpg, etc.).

And **the list**:

- [ ] content/videos/challenges/1-starfield/showcase/contribution2.json
- [ ] content/videos/challenges/1-starfield/showcase/contribution5.json
- [ ] content/videos/challenges/10-dfs-maze-generator/showcase/contribution7.json
- [ ] content/videos/challenges/100-neuroevolution-flappy-bird/showcase/contribution11.json
- [ ] content/videos/challenges/101-may-the-4th-scrolling-text/showcase/contribution1.json
- [ ] content/videos/challenges/103-fire-effect/showcase/contribution4.json
- [ ] content/videos/challenges/108-barnsley-fern/showcase/contribution6.json
- [ ] content/videos/challenges/111-animated-sprites/showcase/contribution1.json
- [ ] content/videos/challenges/113-4d-hypercube-aka-tesseract/showcase/contribution6.json
- [ ] content/videos/challenges/114-bubble-sort-visualization/showcase/contribution10.json
- [ ] content/videos/challenges/114-bubble-sort-visualization/showcase/contribution15.json
- [ ] content/videos/challenges/115-snake-game-redux/showcase/contribution8.json
- [ ] content/videos/challenges/116-lissajous-curve-table/showcase/contribution11.json
- [ ] content/videos/challenges/117-seven-segment-display/showcase/contribution7.json
- [ ] content/videos/challenges/121-logo-interpreter/showcase/contribution3.json
- [ ] content/videos/challenges/122-quick-draw/showcase/contribution1.json
- [ ] content/videos/challenges/124-flocking-simulation/showcase/contribution12.json
- [x] content/videos/challenges/13-reaction-diffusion/showcase/contribution4.json
- [x] content/videos/challenges/13-reaction-diffusion/showcase/contribution6.json
- [ ] content/videos/challenges/130-drawing-with-fourier-transform-and-epicycles/showcase/contribution7.json
- [ ] content/videos/challenges/130-drawing-with-fourier-transform-and-epicycles/showcase/contribution8.json
- [ ] content/videos/challenges/132-fluid-simulation/showcase/contribution3.json
- [x] content/videos/challenges/134-heart-curve/showcase/contribution7.json
- [ ] content/videos/challenges/134-heart-curve/showcase/contribution9.json
- [ ] content/videos/challenges/138-angry-birds-with-matterjs/showcase/contribution3.json
- [ ] content/videos/challenges/14-fractal-trees-recursive/showcase/contribution4.json
- [ ] content/videos/challenges/142-rubiks-cube/showcase/contribution5.json
- [ ] content/videos/challenges/145-ray-casting-2d/showcase/contribution14.json
- [ ] content/videos/challenges/145-ray-casting-2d/showcase/contribution20.json
- [ ] content/videos/challenges/145-ray-casting-2d/showcase/contribution21.json
- [ ] content/videos/challenges/145-ray-casting-2d/showcase/contribution23.json
- [ ] content/videos/challenges/145-ray-casting-2d/showcase/contribution5.json
- [ ] content/videos/challenges/146-rendering-ray-casting/showcase/contribution4.json
- [ ] content/videos/challenges/147-chrome-dinosaur-game/showcase/contribution8.json
- [ ] content/videos/challenges/148-gift-wrapping/showcase/contribution9.json
- [ ] content/videos/challenges/149-tic-tac-toe/showcase/contribution30.json
- [ ] content/videos/challenges/155-kaleidoscope-snowflake/showcase/contribution8.json
- [ ] content/videos/challenges/158-shape-classifier/showcase/contribution1.json
- [ ] content/videos/challenges/159-simple-pendulum/showcase/contribution3.json
- [ ] content/videos/challenges/2-menger-sponge/showcase/contribution1.json
- [ ] content/videos/challenges/2-menger-sponge/showcase/contribution5.json
- [ ] content/videos/challenges/21-mandelbrot-set-with-p5js/showcase/contribution7.json
- [ ] content/videos/challenges/21-mandelbrot-set-with-p5js/showcase/contribution9.json
- [ ] content/videos/challenges/22-julia-set/showcase/contribution3.json
- [ ] content/videos/challenges/29-smart-rockets-in-p5js/showcase/contribution1.json
- [ ] content/videos/challenges/3-snake-game/showcase/contribution11.json
- [ ] content/videos/challenges/3-snake-game/showcase/contribution18.json
- [ ] content/videos/challenges/3-snake-game/showcase/contribution23.json
- [ ] content/videos/challenges/3-snake-game/showcase/contribution5.json
- [ ] content/videos/challenges/30-phyllotaxis/showcase/contribution9.json
- [ ] content/videos/challenges/35-traveling-salesperson/showcase/contribution10.json
- [ ] content/videos/challenges/35-traveling-salesperson/showcase/contribution8.json
- [ ] content/videos/challenges/4-purple-rain/showcase/contribution5.json
- [ ] content/videos/challenges/42-markov-chain-name-generator/showcase/contribution1.json
- [ ] content/videos/challenges/46-asteroids/showcase/contribution2.json
- [ ] content/videos/challenges/46-asteroids/showcase/contribution3.json
- [ ] content/videos/challenges/46-asteroids/showcase/contribution4.json
- [ ] content/videos/challenges/46-asteroids/showcase/contribution7.json
- [ ] content/videos/challenges/58-3d-earthquake-data-visualization/showcase/contribution1.json
- [ ] content/videos/challenges/58-3d-earthquake-data-visualization/showcase/contribution3.json
- [ ] content/videos/challenges/60-butterfly-generator/showcase/contribution1.json
- [ ] content/videos/challenges/64-kinematics/showcase/contribution3.json
- [ ] content/videos/challenges/66-javascript-countdown-timer/showcase/contribution1.json
- [ ] content/videos/challenges/67-pong/showcase/contribution9.json
- [ ] content/videos/challenges/68-breadth-first-search/showcase/contribution1.json
- [ ] content/videos/challenges/68-breadth-first-search/showcase/contribution2.json
- [ ] content/videos/challenges/69-evolutionary-steering-behaviors/showcase/contribution6.json
- [ ] content/videos/challenges/69-evolutionary-steering-behaviors/showcase/contribution9.json
- [x] content/videos/challenges/71-minesweeper/showcase/contribution1.json
- [ ] content/videos/challenges/78-simple-particle-system/showcase/contribution12.json
- [ ] content/videos/challenges/78-simple-particle-system/showcase/contribution7.json
- [ ] content/videos/challenges/83-p5-sketch-chrome-extension/showcase/contribution1.json
- [x] content/videos/challenges/85-the-game-of-life/showcase/contribution5.json
- [ ] content/videos/challenges/86-cube-wave-by-bees-and-bombs/showcase/contribution5.json
- [ ] content/videos/challenges/90-dithering/showcase/contribution5.json
- [ ] content/videos/challenges/91-snakes-and-ladders/showcase/contribution2.json
- [ ] content/videos/challenges/92-xor-problem/showcase/contribution3.json
- [ ] content/videos/challenges/93-double-pendulum/showcase/contribution7.json
- [ ] content/videos/challenges/98-quadtree/showcase/contribution1.json
- [ ] content/videos/challenges/98-quadtree/showcase/contribution5.json
- [ ] content/videos/challenges/c2-collatz-conjecture/showcase/contribution8.json
- [x] content/videos/challenges/c3-hilbert-curve/showcase/contribution16.json
- [x] content/videos/challenges/c3-hilbert-curve/showcase/contribution5.json
- [ ] content/videos/challenges/c4-worley-noise/showcase/contribution13.json
- [x] content/videos/challenges/c5-marching-squares/showcase/contribution1.json
- [ ] content/videos/challenges/c5-marching-squares/showcase/contribution13.json
- [x] content/videos/challenges/c5-marching-squares/showcase/contribution3.json
- [ ] content/videos/data/1-client-side/2-tabular-data/showcase/contribution1.json
- [ ] content/videos/data/1-client-side/2-tabular-data/showcase/contribution2.json
- [ ] content/videos/data/1-client-side/3-graphing/showcase/contribution1.json
- [ ] content/videos/ml5/5-knn-classification/1-build-the-image-classifier/showcase/contribution1.json
- [ ] content/videos/ml5/6-train-your-own-neural-network/1-train-the-model/showcase/contribution1.json
- [ ] content/videos/ml5/6-train-your-own-neural-network/1-train-the-model/showcase/contribution4.json
- [ ] content/videos/ml5/7-posenet/1-finding-keypoints/showcase/contribution1.json
- [ ] content/videos/ml5/7-posenet/1-finding-keypoints/showcase/contribution2.json
- [ ] content/videos/ml5/7-posenet/1-finding-keypoints/showcase/contribution4.json
- [ ] content/videos/ml5/7-posenet/1-finding-keypoints/showcase/contribution5.json
- [ ] content/videos/ml5/8-convolutional-neural-network/1-pixels-as-input/showcase/contribution1.json
- [ ] content/videos/noc/5-autonomous-agents/2-seeking-a-target/showcase/contribution1.json

**Comment by shiffman** [comment]
Wow, thanks for making this list! I'll also note that the passenger showcase image pulls from the video's `index.jpg` if it has one. For example, if you look at the showcase projects missing a thumbnail for the Marching Squares challenge you'll see the example image applied.

<img width="1151" alt="Screen Shot 2023-05-15 at 2 31 23 PM" src="https://github.com/CodingTrain/thecodingtrain.com/assets/191758/4730d4ab-78ef-4993-a542-98554b02c963">

We never made placeholder thumbs for videos associated with tracks (not challenges) but that might be worth considering as well, possibly even building it in as a requirement for tests to pass (though we'd have to fill in all the missing ones first.)

**Comment by kfahn22** [comment]
Some of the showcases were ports to a different language which made it more time-consuming  to grab the image (a consideration when you are adding a ton of them).

**Comment by shiffman** [comment]
I'm doing a pass over all the issues today, is this one still relevant should we work on updating thumbs for more old showcase project or are we covered enough now?

**Comment by kfahn22** [comment]
There are still a lot of showcases that were ported from old site that do not have images.  I think the ones that were relatively easy to grab are done and the ones that are left are more time-consuming /  harder (different languages or platforms) to obtain.   It is a judgement call about whether to close.
