### ISSUE TITLE
OpenSimplexNoise video (Perlin Noise side track?)

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#1087]
I'm working on an additional explanation about Simplex Noise for the introduction of Nature of Code (https://nature-of-code-2nd-edition.netlify.app/introduction/) I'd like to reference my Open Simplex Noise video (https://youtu.be/Lv9gyZZJPE0) for additional context, I don't believe it's on the site. Should we smush it into Nature of Code track or create a new Perlin noise side track?

**Comment by shiffman** [comment]
Also, this is the paragraph I've written in case anyone has any feedback!

> There are many noise implementations in popular programming languages and platforms. Specifically, the p5.js library incorporates a implementation of the original 1983 version, often referred to as "classic Perlin noise". It was succeeded by an improved version in 2001, called Simplex Noise, also developed by Perlin. You can learn more about the history of Perlin noise and its variations over the years in my "What is Simplex Noise?" video on thecodingtrain.com.

**Comment by kfahn22** [comment]
I think you could go either way.  I can add the video to NOC or create a side track.  (BTW I love Exercise I.10.  Reminds me of the surface of the ocean.)

**Comment by kfahn22** [comment]
Do you want to keep the rest of the noise videos where they are in NOC or move to the new Noise side track?

**Comment by kfahn22** [comment]
Also, is there code to link to in a repo somewhere?

**Comment by shiffman** [comment]
> Also, is there code to link to in a repo somewhere?

A quick search of my computer I couldn't find the example I made in the video, but I can recreate it and post it somewhere. This is the link for OpenSimplexNoise.java:

https://github.com/KdotJPG/OpenSimplex2

But it's not a code example so this probably just belongs in references?

**Comment by kfahn22** [comment]
There are newer implementations in the repo.  Should I link to the legacy version?  (No eval function in newer implementations).

**Comment by shiffman** [comment]
> There are newer implementations in the repo. Should I link to the legacy version? (No eval function in newer implementations).

Maybe we link to both? The main repo and then to the legacy version and use the description to provide context?

**Comment by fturmel** [comment]
#1105 was merged back in June, anything left to do regarding this issue?

**Comment by shiffman** [comment]
Yes! I think we can open new issues as needed if there are new ideas or future videos to include.
