### ISSUE TITLE
WebGL tutorials

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#1113]
Is this playlist (from 2017) still relevant enough that it would be useful to add as a side track on the website? 

[https://www.youtube.com/playlist?list=PLRqwX-V7Uu6bPhi8sS1hHJ77n3zRO9FR_](https://www.youtube.com/playlist?list=PLRqwX-V7Uu6bPhi8sS1hHJ77n3zRO9FR_)

I could imagine redoing these and then we could replace them.

I just wrote a couple paragraphs about WEBGL for the Nature of Code book so wondering if I should reference them as an additional resource.

**Comment by kfahn22** [comment]
I think they are a nice basic intro and I can add.  Where did you add the discussion on WEBGL-- I would be interested in reading.

**Comment by kfahn22** [comment]
I am assuming that there have been updates to the library.  Adding an image as texture isn't working the same as in the tutorial (currently working on 18.6).  Ditto for graphics.  Adding text works the same (although I had to add noStroke to eliminate the wireframe, which I don't think you had.)   If I comment out  ambientLight/directionalLight, the image/graphics loads.  Also, am I correct in thinking that the issue with the createGraphics object not being to handle a non-square image has been resolved?  Am I missing something, or should I just note the changes?  (Also, do you have  the code examples somewhere?)  I have recreated one here, but wondering if you already have it in a repo. https://editor.p5js.org/kfahn/sketches/UiotWEhYM

**Comment by shiffman** [comment]
> I think they are a nice basic intro and I can add. Where did you add the discussion on WEBGL-- I would be interested in reading.

It's in the section on additive blending! https://nature-of-code-2nd-edition.netlify.app/particles/#example-49-additive-blending

**Comment by kfahn22** [comment]
I have everything done, but I wan't sure whether we were still adding the video numbers.  Are they still important?  The other thing to note is that the sketch loading the obj model gets a loadStrings warning and   I was not able to figure out why.

**Comment by shiffman** [comment]
I don't think the numbers are necessary, no! Closing this now as it's covered by #1121! I'll look at the obj model sketch to see if I can figure that out.
