### ISSUE TITLE
p5 tips and tricks

### ISSUE THREAD

**Issue by dipamsen** [CodingTrain/thecodingtrain.com#1118]
Video suggestions to be added to "p5 tips and tricks" track
- [Custom Shapes](https://www.youtube.com/watch?v=76fiD5DvzeQ)

**Comment by shiffman** [comment]
Yes, this would be great!

**Comment by shiffman** [comment]
Also, let's add a page for 2D arrays! It's referenced in several videos on the site:

https://github.com/search?q=repo%3ACodingTrain%2Fthecodingtrain.com%20OTNpiLUSiB4&type=code

This came up b/c I am also referencing this video in the Nature of Code book and I'd like to link to thecodingtrain.com.

Open to other places where this video could go?

https://youtu.be/OTNpiLUSiB4

**Comment by dipamsen** [comment]
@shiffman If you still want to link to the 2d arrays video from NoC, you can merge #1162

**Comment by fturmel** [comment]
#1162 was merged, I think we can close this issue?

**Comment by shiffman** [comment]
Indeed!
