### ISSUE TITLE
Order of side tracks

### ISSUE THREAD

**Issue by kfahn22** [CodingTrain/thecodingtrain.com#1122]
There are a lot of side tracks at this point.  I am wondering if alphabetizing the order would be a good idea--it might make it easier to locate a track.

**Comment by shiffman** [comment]
This is a great point! The order is currently managed by this file:

https://github.com/CodingTrain/thecodingtrain.com/blob/main/content/tracks/index.json

The goal of this file is to prioritize important tracks towards the top but maybe the arbitrariness of that is confusing. My preference would be to improve the "filter by topic" feature on the tracks page and curate the keywords in a way that makes tracks easy to find. (This is currently how I look for the side track I'm searching for.)

**Comment by kfahn22** [comment]
As it currently stands, the main tracks (which I think are supposed to be  the most important) are first, followed by the side tracks which are in alphabetical order (with the exception of workflow which comes at the beginning because the folder name is 2018-workflow).  I am not sure that this is obvious, however, as it would be easy to miss the MAIN TRACK, SIDE TRACK label.

**Comment by shiffman** [comment]
Yeah, this works for me, but I'm open to ideas to improve it!

**Comment by kfahn22** [comment]
Closed as completed.
