### ISSUE TITLE
Possible redirect to showcase form

### ISSUE THREAD

**Issue by dipamsen** [CodingTrain/thecodingtrain.com#1127]
I was thinking if it would be beneficial if we had a potential redirect  eg. `/submit` or similar, which would redirect to the passenger showcase form.

```
https://thecodingtrain.com/guides/passenger-showcase-guide
```

**Comment by shiffman** [comment]
Yes, I agree, great idea!

**Comment by shiffman** [comment]
Thanks again to @M0nica!
