### ISSUE TITLE
Can't see top of site in Safari

### ISSUE THREAD

**Issue by tommy-gilligan** [CodingTrain/thecodingtrain.com#1147]
![Screenshot 2023-07-06 at 3 46 26 pm](https://github.com/CodingTrain/thecodingtrain.com/assets/7865781/5f486e1a-c498-40d4-ab9a-d8083f89dc5a)

Can't scroll to the top

**Comment by fturmel** [comment]
Thanks for reporting! I'm not seeing this behavior on Safari 16.5.1, could you share steps to reproduce, and your browser / OS versions?
