### ISSUE TITLE
regarding output 

### ISSUE THREAD

**Issue by jahnavi-053** [CodingTrain/thecodingtrain.com#1175]
hello sir 
actually i am facing a problem in display of the output for the project .i am getting the blank output with the layout but the letters are not filling in that 
can you please tell me something about this.

**Comment by kfahn22** [comment]
Would you be able to provide some more information.  What is the project?  What are you trying to render?  Do you have a link to your code?   Also, there is a help-forum on the Coding Train Discord where you ask questions.

**Comment by shiffman** [comment]
Closing this issue, help with code should go to discord: https://thecodingtrain.com/discord
