### ISSUE TITLE
Side Track for p5.js images/pixels/video

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#1249]
I'm teaching these concepts in my NYU course starting this week and would love to have a side track with all the code examples organized and updated video descriptions.

https://www.youtube.com/playlist?list=PLRqwX-V7Uu6aKKsDHZdDvN6oCJ2hRY_Ig

**Comment by shiffman** [comment]
I discovered that @jht1493 created the examples in the p5.js web editor which will save a lot of time here!

**Comment by shiffman** [comment]
Thanks to @kfahn22 this is mostly all done! Will leave open in case we want to add more videos from the playlist (slit scan, any others?), other small things:

* track description
* video descriptions
* expand topics
* add more related challenges
* include pixel based challenges?

**Comment by kfahn22** [comment]
I will add the remaining two videos.

**Comment by fturmel** [comment]
I think this track has been completed? https://thecodingtrain.com/tracks/pixels

**Comment by kfahn22** [comment]
Yes, I think so.  We might want to add the latest two challenges to related challenges, though.

**Comment by shiffman** [comment]
@kfahn22 agreed! That can be done separately from this issue. Probably a good idea anytime a new challenge is published to look around and see where it might make sense to link from! We can address this in #1387 for the new video!
