### ISSUE TITLE
Correction Timecodes

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#1252]
YouTube now offers corrections timecodes, I just tried adding one for this video:

https://thecodingtrain.com/tracks/pixels/pixels/painting-with-pixels

I manually added it to the YT description:

```
Corrections: 
02:40 This old example is not using classes in JavaScript. Check the accompanying code for an updated version!
```

<img width="435" alt="Screen Shot 2023-10-25 at 11 40 31 AM" src="https://github.com/CodingTrain/thecodingtrain.com/assets/191758/269792f3-d988-493f-bae6-0c7f87a64137">

Maybe we should consider adding this to the JSON for each video as well as the description generator?

**Comment by dipamsen** [comment]
Would this need to be implemented on the website as well? YT doesn't seem to show the pop-up inside embeds.

**Comment by shiffman** [comment]
> Would this need to be implemented on the website as well? YT doesn't seem to show the pop-up inside embeds.

I don't think it needs to be no, but since I generate the descriptions from the JSON, I'd love to have it there for safe-keeping and consistency.We could render it to another "tab" like references, videos, etc. "Corrections" also. 

This is pretty low priority as I only just used it for the first time on this one video... and don't know if I really plan on adding it to more places in the future. In theory, though, it's a great feature to be able to annotate mistakes and things that have changed.

**Comment by fturmel** [comment]
Can we close this issue since #1282 was merged?

**Comment by shiffman** [comment]
Yes! Thanks for the reminder!
