### ISSUE TITLE
bug/feat: exact match should be first result in search dropdown

### ISSUE THREAD

**Issue by dipamsen** [CodingTrain/thecodingtrain.com#1264]
![image](https://github.com/CodingTrain/thecodingtrain.com/assets/59444569/887f4830-5f56-422a-8809-3aabdb72dd5e)

Here, preferably "data" should be listed as the first search result, or it leads to a weird interaction where typing "data" and <kbd>Enter</kbd> opens up the search results for "COCO dataset".

**Comment by shiffman** [comment]
ah! looks like it is maybe doing it in alphabetical order? We could implement a [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) (I actually had this on my list to do a quick coding challenge at one point heh) or similar algorithm maybe? Or perhaps there's a more standard way of sorting results that can be applied here.
