### ISSUE TITLE
"Topics" for all challenges and tracks

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#128]
I need to do a pass to clean-up, add, and clarify topics. This thread can track the discussion.

Starting with:
* I have "basics" and "for beginners" as a tag for videos (Code! Track, challenges, and some Nature of Code videos). I think maybe the topic should be "beginner friendly" (open to suggestions!) and that it should not be applied to Nature of Code videos.

**Comment by shiffman** [comment]
Bringing discussion from #146, should Topics all be capitalized or all lower case? Is "tag" a more clear term than "topic"?

**Comment by fdoflorenzano** [comment]
@shiffman good question! I think it's fine either way. All lower case as general rule I think sounds good, unless there's proper nouns in there. Like most languages, they should be written "Python", "JavaScript" and others like "GitHub". Are you concerned of getting more errors in the future where contributions have different spellings of the same tag?

For the second question, I think tag is a bit generic, as it also applies to languages. Topics, to me, is clear enough.

**Comment by shiffman** [comment]
Closing with #799! Always more work on topics to be done but I think we have a good foundation now and can open new issues as needed.
