### ISSUE TITLE
simplify YT links in description generator

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#1280]
I noticed how that YT renders the YT icon + video/playlist title in the description itself. So having the additional text is likely redundant:

<img width="340" alt="Screen Shot 2023-11-03 at 6 35 14 PM" src="https://github.com/CodingTrain/thecodingtrain.com/assets/191758/69f2b2ec-81bc-437b-9512-c4023834bdbf">
<img width="537" alt="Screen Shot 2023-11-03 at 6 35 09 PM" src="https://github.com/CodingTrain/thecodingtrain.com/assets/191758/65550856-aea5-4842-a2e2-b4ea5af6ce44">

**Comment by dipamsen** [comment]
found an edge case:

![image](https://github.com/CodingTrain/thecodingtrain.com/assets/59444569/b2f840a5-7c56-42d2-8a2e-5459c936144a)

**Comment by Highlandword9** [comment]
YouTube may change how they render links again.

**Comment by shiffman** [comment]
> found an edge case:
> 
> ![image](https://private-user-images.githubusercontent.com/59444569/280543294-b2f840a5-7c56-42d2-8a2e-5459c936144a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NjkzMDAsIm5iZiI6MTcxMDg2OTAwMCwicGF0aCI6Ii81OTQ0NDU2OS8yODA1NDMyOTQtYjJmODQwYTUtN2M1Ni00MmQyLThhMmUtNTQ1OWM5MzYxNDRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDE3MjMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhNWNjNzI1ZmI1YTc5NDUzYWJjZDYyYjY4MzVmZTM4ZjRmZWY3MjExYzMxYzk4YTc0ZTg5NzllYzMxZjZlMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GwYFDBNkpqbJjPmsqfUO7Zz7NLuNIr5WnVbRRGqJ74U)
> 
> One solution could be to only hide the text for YouTube links.

I think this would make sense to do, what do you think @dipamsen?
