### ISSUE TITLE
Thumbnail Aspect Ratio on About Page

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#129]
Just noting that we should probably update the thumbnail aspect ratio on the about page to match the challenges page.

About page:
<img width="1670" alt="Screen Shot 2022-05-12 at 3 05 18 PM" src="https://user-images.githubusercontent.com/191758/168149852-31f38540-a57e-4402-89cd-183291728255.png">

<img width="1640" alt="Screen Shot 2022-05-12 at 3 06 11 PM" src="https://user-images.githubusercontent.com/191758/168149940-f5b9cd26-4450-4349-8c2f-146083ecc60a.png">

Also, @fdoflorenzano should the titles on the challenges page be bolded like they are on the about page? I think that might look nice but defer to you all!

**Comment by fdoflorenzano** [comment]
I agree the aspect ratio should match. I had a similar thought about it.

About the bolded titles, I'm not sure. There's too things happening there, the titles are bold and black, which brings a lot of contrast. This all also relates to color contrast concerns that I have, so I would probably focus on that aspect separately.

**Comment by shiffman** [comment]
> About the bolded titles, I'm not sure. There's too things happening there, the titles are bold and black, which brings a lot of contrast. This all also relates to color contrast concerns that I have, so I would probably focus on that aspect separately.

Got it! I don't have a preference and trust you all on your design decisions! I just had noticed it was different so pointed it out, the aspect ratio is the more important note here!
