### ISSUE TITLE
Problem With Discription

### ISSUE THREAD

**Issue by shoonygog** [CodingTrain/thecodingtrain.com#1304]
There are three **p5.js** links when its not **p5.js**, its **AppleSoft Basic**.

**Comment by shiffman** [comment]
Hello! Can you be more specific about where you are seeing this description? Which video and on which website page? Thank you!!

**Comment by shiffman** [comment]
This is fantastic!!! A few comments:

Chapter 2: Maybe remove the squid?  For me it's better to reveal it in the context of chapter 3 (oscillation)? You could also then emphasize the fish going after the food. Oh, and could the bugs do the "dance" that is featured in illustration 2.10?

![image](https://github.com/CodingTrain/thecodingtrain.com/assets/191758/ad65eb74-1f18-4e55-b382-586302936454)


Chapter 3: Could you make the little bugs were more prominent (The fish and the food can be in the background)? With the bugs, could you draw something to visually show that their wings are flapping?  This is specifically in the oscillation prompt. And then the squid's legs appear as new here to represent the sine waves!

Chapter 6: I'm not seeing the physics libraries so much here. I think the Octopus does represent the "soft body character"  idea with tentacles quite well. Is there any way to show collisions somehow? I realize it's hard without this being animated. Could there be an obstacle the fish are bumping into?

**Comment by shoonygog** [comment]
On YouTube, And on the 3 episodes of Coding Apple Basic.

**Comment by fturmel** [comment]
@shoonygog I can't find these either, sorry. Can you share more details and post screenshots and/or links?

**Comment by shiffman** [comment]
There hasn't been a response in quite some time to this issue so I'm going to close for now. If we can pinpoint the problem happy to re-open!
