### ISSUE TITLE
Deploy Commands code

### ISSUE THREAD

**Issue by wgduxbury** [CodingTrain/thecodingtrain.com#1311]
Where is the step by step discord bot guide with the 'deploy commands' code

**Comment by dipamsen** [comment]
Here it is: https://github.com/CodingTrain/Discord-Bot-Examples/tree/main/01-discordjs

The readme file in this directory contains the step by step instructions that Dan followed in the video, and the deploy commands script is also in there. (It is also linked in the YouTube description!)
