### ISSUE TITLE
link directly to a "part" of a coding challenge?

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#1319]
I was just linking the TF-IDF challenge from my syllabus and noticed that the URL only goes to part 1 of the challenge

https://thecodingtrain.com/challenges/40-word-counter

I wonder if there's an easy way I could link directly to part 3 (TF-IDF) with something like

`https://thecodingtrain.com/challenges/40-word-counter#part-3`

or

`https://thecodingtrain.com/challenges/40-word-counter#tf-idf`

**Comment by loic-brtd** [comment]
I can try to implement this feature 🙂 I think the easiest way would be to use `#part-3` as it doesn't require us to add (or generate) a slug for each part. Also it's unlikely that the order of the parts will change for existing coding challenges.
