### ISSUE TITLE
Minor UI adjustments 

### ISSUE THREAD

**Issue by raj-jaiswal** [CodingTrain/thecodingtrain.com#140]
While surfing through the website,I found these things that shouldn't take long to adjust.

On the landing page :

![Screenshot_20220521-064805_Chrome](https://user-images.githubusercontent.com/59106789/169629481-0b5491e1-1936-4356-8b95-c4a51c2ed9d3.png)

The YouTube membership option should start below the title "Support" unless intentional.

![Screenshot_20220521-065605_Chrome](https://user-images.githubusercontent.com/59106789/169629556-46502f86-1fd4-4db0-aeba-6a350fd07713.png)

The getting started,videoes and passengers area doesn't feel centered or aligned to the text above

On mobile version :

![Screenshot_20220521-065120_Chrome](https://user-images.githubusercontent.com/59106789/169629642-acacd492-00b5-4ebb-8f99-fb36e29761ae.png)

Here,The margin of the text is inconsistent (maybe it shouldn't wrap).

![Screenshot_20220521-065048_Chrome](https://user-images.githubusercontent.com/59106789/169629726-bf4c2d53-b9c3-4e27-b2c2-92b66c41757d.png)

In the support area,the white spacing seems a bit too much, making the buttons a bit more wider should help.

![Screenshot_20220521-065108_Chrome](https://user-images.githubusercontent.com/59106789/169629761-d92b19c4-75bc-4038-a140-e86e76642f30.png)

There seems to be no margin on images which feels a bit wrong. My suggestion would be to make the images at same margin as text or adding a global padding to the container.

On the coding challenges page :

![Screenshot_20220521-065313_Chrome](https://user-images.githubusercontent.com/59106789/169629849-ed04fe4c-5d70-4d9c-abfa-a6415584a801.png)

The contrast here is a bit less which makes it hard to read. Also,python is repeated 2 times.

On the tracks section :

![Screenshot_20220521-070104_Chrome](https://user-images.githubusercontent.com/59106789/169629947-91d2fae5-b83a-4b1b-a7f4-6874ee4ef05c.png)

This one might be noticed already but the description is bleeding.

**Comment by fdoflorenzano** [comment]
> On the landing page :
> The YouTube membership option should start below the title "Support" unless intentional.

That's intentional.

> 
> The getting started,videoes and passengers area doesn't feel centered or aligned to the text above

If I understood what you mean right, that's also intentional.

> On mobile version :
> Here,The margin of the text is inconsistent (maybe it shouldn't wrap).

That is a bit odd, and can be reviewed.

> In the support area,the white spacing seems a bit too much, making the buttons a bit more wider should help.

I'm not sure to what white spacing you are referencing.

> There seems to be no margin on images which feels a bit wrong. My suggestion would be to make the images at same margin as text or adding a global padding to the container.

That's also intentional and part of the site's design.

> On the coding challenges page :
> The contrast here is a bit less which makes it hard to read. Also,python is repeated 2 times.

That's already noted in #121 

> This one might be noticed already but the description is bleeding.

That was already address in #132

**Comment by fdoflorenzano** [comment]
> By whitespace i meant the gap between buttons and texts. Wider here means vertically higher.

I'm not sure that's the issue there, that block padding for buttons are used everywhere else. Maybe there it's the fact that there so many similar section one after the other that take so much space. Maybe reducing the vertical height of the sections before the buttons helps?

**Comment by raj-jaiswal** [comment]
Yeah. That might work

**Comment by shiffman** [comment]
Is this issue resolved, can I close?

**Comment by fdoflorenzano** [comment]
Most of the issues were resolved on our end. I think the last one mentioned wasn't, but wasn't super pressing on DSI's end at least.

**Comment by shiffman** [comment]
Thank you @fdoflorenzano! I'm going to close for now @raj-jaiswal please feel free to re-open or create a new issue if there are important things you think I should look at or address still!! Thank you!!!
