### ISSUE TITLE
Space in URL for video "neural-networks/3-perceptron-part 2"

### ISSUE THREAD

**Issue by loic-brtd** [CodingTrain/thecodingtrain.com#1404]
Hi!

I noticed there's a space instead of a dash in the name of this folder : [content/videos/neural-networks/3-perceptron-part 2](https://github.com/CodingTrain/thecodingtrain.com/tree/main/content/videos/neural-networks/3-perceptron-part%202)
This leads to having this video URL : https://thecodingtrain.com/tracks/neural-networks/neural-networks/3-perceptron-part%202 (%20 being a url-encoded space).

Should we replace it with a dash or is it too late?

**Comment by dipamsen** [comment]
should be fine, the link is not linked in the video description
