### ISSUE TITLE
More noise videos to noise track

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#1407]
https://www.youtube.com/watch?v=ikwNrFvnL3g&list=PLRqwX-V7Uu6ZV4yEcW3uDwOgGXKUUsPOM&index=6
https://www.youtube.com/watch?v=D1BBj2VaBl4&list=PLRqwX-V7Uu6ZV4yEcW3uDwOgGXKUUsPOM&index=7

these could go in the noise track or the noise and noc track.

Also, the worley noise challenge could go in the noise track

**Comment by kfahn22** [comment]
Closing this as completed.
