### ISSUE TITLE
/tracks/lang:Python+topic:all/ doesn't exist

### ISSUE THREAD

**Issue by Heinrich-XIAO** [CodingTrain/thecodingtrain.com#146]
When I go to /tracks, there's filter by language and there's Python and python, python exists and I can click on it, but Python doesn't.

**Comment by shiffman** [comment]
@fdoflorenzano I am going to fix this and change the topics to all be lowercase "python" but do you think the topics and languages should maybe not be case sensitive?

**Comment by fdoflorenzano** [comment]
@shiffman I answered in #128

**Comment by shiffman** [comment]
I'm going to close this and we can track the work in #401
