### ISSUE TITLE
ml5 code is missing from youtube descripton

### ISSUE THREAD

**Issue by DrSpaniel** [CodingTrain/thecodingtrain.com#1466]
in the link https://www.youtube.com/watch?v=q6cwxORPDo8

the link

https://thecodingtrain.com/Courses/ml5-beginners-guide/6.2-ml5-save-data.html

is dead, and does not redirect properly.

**Comment by dipamsen** [comment]
The correct website url is https://thecodingtrain.com/tracks/ml5js-beginners-guide/ml5/6-train-your-own-neural-network/2-save-data

**Comment by shiffman** [comment]
I've updated the video description thank for flagging @DrSpaniel!

**Comment by DrSpaniel** [comment]
thank you for the amazing courses!
