### ISSUE TITLE
single pixel gap in nav dropdown

### ISSUE THREAD

**Issue by dipamsen** [CodingTrain/thecodingtrain.com#1486]
![image](https://github.com/CodingTrain/thecodingtrain.com/assets/59444569/77c9bf43-881e-43e3-842b-58094817ba4d)

**Comment by lcgraves** [comment]
Hi @dipamsen, I can't seem to reproduce the behaviour. I took screenshots in Safari and Chrome browsers and don't see the behaviour you observed.

Here's a screenshot in Safari browser:

<img width="653" alt="Screenshot 2024-03-18 at 9 24 31 AM" src="https://github.com/CodingTrain/thecodingtrain.com/assets/144481646/03be7b49-9c62-474c-bb5c-29842408cc89">


And here's a screenshot in Chrome browser:

<img width="437" alt="Screenshot 2024-03-18 at 9 30 26 AM" src="https://github.com/CodingTrain/thecodingtrain.com/assets/144481646/f46dc1e8-5933-4115-9a6d-bce2c10691aa">

**Comment by dipamsen** [comment]
That's interesting, I see it in both Chrome and Firefox:

Windows 11 23H2 64 bit

Firefox Version 123.0.1 (64-bit)
![image](https://github.com/CodingTrain/thecodingtrain.com/assets/59444569/3a962cf7-e595-4b49-8aa0-447dc4c1cb29)

Chrome 122.0.6261.129 (Official Build) (64-bit)
![image](https://github.com/CodingTrain/thecodingtrain.com/assets/59444569/ba82768f-7cde-4ed4-934d-182d79fa5397)

**Comment by shiffman** [comment]
I can't reproduce it on a mac either! Not sure how to best approach this but open to suggestions, thanks for finding this @dipamsen!

**Comment by fturmel** [comment]
Same, can't reproduce on macOS (Chrome, Firefox and Safari) 🤷

(The menu font looks bad too! Mismatched height between characters...)

Would be interesting to know if all Windows users are experiencing this, or if it's just your setup.

Some thoughts and ideas to explore:

1. Could it be linked to the pixel density of your display? We're most likely all on retina displays (over 200 PPI) on mac, which may be why we don't see the same thing as you.
2. Are you scaling the display or text at the OS level? (accessibility features)
3. Are you using your display's native resolution or are your slightly below/above? That could explain the subpixel/blurry stuff happening, and the gap could be related.
4. GPU drivers?

In your original screenshot, the hairline borders at the bottom (which should be 1px solid) seem to misalign at the subpixel level and the red one is anti-aliasing (lighter at the bottom).

![CleanShot 2024-03-21 at 12 50 25@2x](https://github.com/CodingTrain/thecodingtrain.com/assets/4009209/e6ba4ac7-3f20-446b-b679-411bfa644501)

The baseline for the menu buttons is 50px on the site, so the actual pixel size on display should be a factor of 50. I don't know if you upscaled your later screenshots, but the butons seem to be at a height of ~120px. Makes me think my points 2 and/or 3 could be at play?

![CleanShot 2024-03-21 at 13 54 32@2x](https://github.com/CodingTrain/thecodingtrain.com/assets/4009209/7dfcc24b-92fa-4e7d-9183-c6de6cb9854c)

**Comment by dipamsen** [comment]
All my previous screenshots were taken after zooming in (magnification via touchpad on chrome, not sure what this feature exactly is called). Here are the same page screenshots without any zooming:

Home Page

![Screenshot 2024-03-21 234709](https://github.com/CodingTrain/thecodingtrain.com/assets/59444569/9f63890b-dc10-4f3b-935e-6c9a844ed1c2)

Showcase Guide Page

![image](https://github.com/CodingTrain/thecodingtrain.com/assets/59444569/da1586eb-745a-4032-8ae1-f52784e19117)

**Comment by dipamsen** [comment]
Changing back to 100% does fix all the issues:

![image](https://github.com/CodingTrain/thecodingtrain.com/assets/59444569/39f12bef-0181-4218-9a20-8e59b8723acd)

Though it does make everything on my screen extremely tiny, so I'll go back to 125%, or change the screen resolution.
