### ISSUE TITLE
site domain - codingtrain.com or thecodingtrain.com?

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#1515]
`codingtrain.com` became available recently and I was able to purchase it. It is currently set up to forward to `thecodingtrain.com`. What do people think about me switching the site over and having `thecodingtrain` -> `codingtrain`? Are there unintended consequences I'm not thinking of? Is one more preferable than others? (I tend to use @TheCodingTrain on social platforms due to @codingtrain not typically being available.)

**Comment by curiousHG** [comment]
I like thecodingtrain more 😋

**Comment by shiffman** [comment]
I am going to leave the canonical url for the website as https://thecodingtrain.com/ but codingtrain.com can also be used as needed!
