### ISSUE TITLE
Create Coding Challenge Pages

### ISSUE THREAD

**Issue by btb331** [CodingTrain/thecodingtrain.com#155]
It might be useful, but don't feel you have to use it.. choo choo choo

https://docs.google.com/spreadsheets/d/1zt8KquMZN_j2-j4ezMsgeq-sRrgoCEAROwFS6LTS8oQ/edit#gid=1236591781

**Comment by shiffman** [comment]
This is fantastic thank you!

**Comment by lobertrand** [comment]
I updated this spreadsheet to match with the latest ported challenges :)
If we want to keep this spreadsheet up to date, maybe we should mention it in the "Maintaining the website" guide?

**Comment by lobertrand** [comment]
> Yes, I agree! Would you like to add it via pull request @lobertrand? 

Yes, I'm gonna do this :)

**Comment by shiffman** [comment]
@allcontributors add @btb331 for projectManagement

**Comment by btb331** [comment]
Thanks! Just checking you don't need me to do anything?

**Comment by shiffman** [comment]
I think this can be closed now that all the challenges are on the site!
