### ISSUE TITLE
Social Sharing (Twitter)

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#1610]
For the Nature of Code book we're trying to get the social sharing image preview working for twitter! https://github.com/nature-of-code/noc-book-2/issues/938 but we can't figure it out. Noticed it's also not working for thecodingtrain.com.

https://twitter.com/CodingTrainBot/status/1795447777532489867

![Screen Shot 2024-05-28 at 9 32 04 AM](https://github.com/CodingTrain/thecodingtrain.com/assets/191758/58ff54fa-e650-4362-a8fa-8d86cd8032d3)

Works in Discord for comparison

![Screen Shot 2024-05-28 at 9 32 10 AM](https://github.com/CodingTrain/thecodingtrain.com/assets/191758/2c8e2e5f-0e0e-4bce-9b60-06e4ce27b4f8)

**Comment by fturmel** [comment]
See https://github.com/nature-of-code/noc-book-2/issues/938#issuecomment-2135572849 - maybe we should also update the Twitter meta data to use "name" per their docs.
