### ISSUE TITLE
update typos in video descriptions and timecodes

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#1620]
See: #1618

At the moment this can only be done by me manually, but I am open to giving edit access to video descriptions to someone and/or investigating doing these updates via the YouTube API.

**Comment by kfahn22** [comment]
I can handle this.

**Comment by kfahn22** [comment]
The typos in the challenges have been fixed.

**Comment by shiffman** [comment]
Wow!! So this can be closed?

**Comment by kfahn22** [comment]
updated matter.js and toxiclibs video descriptions

**Comment by kfahn22** [comment]
updated more-p5/pixel array

**Comment by kfahn22** [comment]
updated web sockets

**Comment by dipamsen** [comment]
@shiffman I am working on a script to automate updating the description via the YouTube API...

**Comment by kfahn22** [comment]
Love the idea of the automatic update -- in the meantime, ml5 and sound have been updated.

**Comment by kfahn22** [comment]
Updated the neural network videos.  I believe  I have updated everything.

**Comment by shiffman** [comment]
@kfahn22 I believe this issue can be closed! Please go ahead if you agree!

**Comment by kfahn22** [comment]
Close as completed.
