### ISSUE TITLE
Missing Coding Challenges 73 and 118

### ISSUE THREAD

**Issue by dipamsen** [CodingTrain/thecodingtrain.com#1627]
- [ ] Coding challenge 73 - Acrostic (https://www.youtube.com/watch?v=jwoK5WKVXGw)
- [ ] Coding challenge 118 - Mastodon Fractal Tree Bot (https://www.youtube.com/watch?v=luxczHFn1rU)

in case someone wants to port these, [here is a helpful tool](https://github.com/dipamsen/CT-content-porter) to get a starter json file, based on data from the [old website](https://codingtrain.github.io/website-archive/CodingChallenges/)

**Comment by fturmel** [comment]
@shiffman @jasontheillustrator Are there thumbnails for these challenges that we could use?

**Comment by jasontheillustrator** [comment]
Looks like we don't have any new thumbnails. The current thumbnails are older ones that @shiffman might have access to.

**Comment by shiffman** [comment]
Apologies for the slowness in replying/reviewing I'm traveling until August 6. @jasontheillustrator can make new thumbnails for the YT videos but for the `index.jpg` files that go along with the challenges we usually just take the visual element frmo the thumbnail or custom design our own (w/o a photo of me or text). @kfahn22 has made most of them in fact! 

I'm happy for anyone to just create something for these two challenges and I'll work with @jasontheillustrator to upload the YT thumbs themselves!

**Comment by jasontheillustrator** [comment]
I made some thumbnails for you.
![CC-118-Mastodon-Fractal-Tree-pt1-Website-Thumbnail](https://github.com/user-attachments/assets/734179ec-122d-413b-9729-36f6072c693e)

![CC-73-Acrostic-Website-Thumbnail-B](https://github.com/user-attachments/assets/d1c9e3fb-a1d9-47f7-89bf-d71220c8ea15)

**Comment by fturmel** [comment]
Thanks @jasontheillustrator! 

For challenge 118, I'm wondering if a thumbnail only showing the fractal tree would be misleading. The videos are mostly about using the Mastodon API in Node.js to make a bot, and executing a Processing sketch from the command line. The tree fractal is not coded on screen, I believe it's one of the official Processing [examples](https://processing.org/examples/tree.html) lightly altered to demonstrate the bot behavior.

For challenge 73, @kfahn22 updated the source code to make it functional again, and provided a matching thumbnail in #1671 so maybe we should go with that one?

**Comment by jasontheillustrator** [comment]
Thanks for the feedback. I think it's probably best if @shiffman weigh in on this.

**Comment by shiffman** [comment]
What if we try a thumbnail like this? The only thing is the tree angle in the render might not actually be 52 degrees, an easter egg for the detail-oriented viewer?

![image](https://github.com/user-attachments/assets/586b0ab5-cca3-4fb2-a9a4-901dd502e58e)

**Comment by kfahn22** [comment]
Closing this because all Coding Challenges are not on website!
