### ISSUE TITLE
Top Nav Menu Questions

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#163]
This is such a tiny detail, but I'm noticing the alignment of the menus is a little bit funky. I think the text is centered in the menu options and it looks like:

<img width="368" alt="Screen Shot 2022-06-05 at 5 26 11 PM" src="https://user-images.githubusercontent.com/191758/172071318-51395e9d-5516-4fd6-a20f-31ed50196bc3.png">

Would it look cleaner to left align the text so that `tracks`, `challenges`, and `FAQ` line up with `videos`? Or should the videos box be larger so that it is the same width as the options when unfurled below.

I suppose I have the same questions for under "Community"?

<img width="284" alt="Screen Shot 2022-06-05 at 5 26 16 PM" src="https://user-images.githubusercontent.com/191758/172071321-c0f6b82f-53e5-4514-a039-17f9976def4b.png">

And while I'm here should "FAQ" go under "COMMUNITY" or "ABOUT" instead of "VIDEOS"?

**Comment by fdoflorenzano** [comment]
A proposal was added in #159 , what do you think? Text was aligned to the left and "FAQ" was moved with "ABOUT".

**Comment by fdoflorenzano** [comment]
> Ah, sorry I missed looking at this specifically with the pull request! It's great! I like the alignment. One thing that is a bit odd is that for "ABOUT", it has "FAQ" under but "ABOUT" is also clickable. With "VIDEOS" and "COMMUNITY" only the options below are clickable. I don't really mind this but thought I would point it out?

Yes, actually I had to add that behavior, before it wasn't possible. If a menu item had a sub-menu, then it couldn't have a URL. I wanted to add a new word to combine about and FAQ, but I couldn't come up with something good. Any ideas? Another thing is that horizontal space is precious so a very long word can mess up the rest of the bar.

> It feels a little bit like the options that unfurl should have a minimum width of the parent above but this is such a TINY detail and I defer to the designers wisdom here!

I can try and check how to make that work and see how it feels. Again, widths are kind of tricky here so we have to be careful.

**Comment by shiffman** [comment]
> I can try and check how to make that work and see how it feels. Again, widths are kind of tricky here so we have to be careful.

I'm good with it as is! It's such a small detail!

> I wanted to add a new word to combine about and FAQ, but I couldn't come up with something good. Any ideas? Another thing is that horizontal space is precious so a very long word can mess up the rest of the bar.

@elizabethslash and I are meeting tomorrow maybe she'll have a thought about this one!

**Comment by shiffman** [comment]
@bravomartin and @runemadsen what do you think about this? I'm fine with the website as it is so happy to close unless you think it's important to further develop the language for the nav bar.

**Comment by bravomartin** [comment]
I don't mind the menu items having different widths than the parent. 
I think it is also consistent with the rules of the system, where the vertical grid takes preeminence over the vertical grid. So my vote would be to keep it as is and close this issue.

**Comment by shiffman** [comment]
Agreed! Thank you @bravomartin!
