### ISSUE TITLE
Linking to Code Examples

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#167]
Just noting this discussion about moving all the coding challenge example code to this repo.

https://github.com/CodingTrain/Coding-Challenges/issues/1

We'll also want to do the same for all the tracks! Lots to do!

Also, I forgot that I think we implemented having thumbnail images for the code examples! Let's try adding some of these!

See https://github.com/CodingTrain/thecodingtrain.com/issues/68#issuecomment-1043285167.

**Comment by shiffman** [comment]
@fdoflorenzano I have to apologize, I forgot where we left this how it is supposed to work? Do you recall?

**Comment by shiffman** [comment]
Just noting that the code example images question is resolved but I'm leaving this open as the Coding Challenges repo is still in progress!

**Comment by dipamsen** [comment]
Update: All Code Examples for Coding Challenges have been added in this repo: https://github.com/CodingTrain/Coding-Challenges. The code example links in the website which earlier pointed to `CodingTrain/website` should be changed to `CodingTrain/Coding-Challenges`.

Changes: 
- All challenges are in the root of the repo. The directories are named `###_ChallengeName` (`ChallengeName` is same as old repo)
- The directory names are no longer prefixed with `CC_`

Example:

```
Old: https://github.com/CodingTrain/website/tree/main/CodingChallenges/CC_134_Heart_Curve_2/P5
New: https://github.com/CodingTrain/Coding-Challenges/tree/main/134_Heart_Curve_2/P5
```

**Comment by shiffman** [comment]
Amazing! @dipamsen would you like to add documentation about this to the site maintenance guide? Then we can close this issue. So appreciate your help here!!!!

**Comment by shiffman** [comment]
This is now in the guide!
