### ISSUE TITLE
`shiffman.net` redirect to `thecodingtrain.com` not working with `https` protocol

### ISSUE THREAD

**Issue by fturmel** [CodingTrain/thecodingtrain.com#1676]
Adding it here so there's more visibility. I feel like we've discussed this on Discord before but it hasn't been corrected.

Maybe related https://github.com/shiffman/shiffman.net/pull/131

The `http://` redirection works, but with `https://` is just a generic Squarespace landing page.

Because of the [HSTS response header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security), it's easy to get in a state were we can never really go back to `http://` without manually purging the HSTS policy for the domain in the browser. Modern browsers also have an HTTPS-only mode available and would never land on the non-secure version of the URL to begin with.

I don't know how the current implementation works, but can this not simply be handled by their domain forwarding service? https://support.squarespace.com/hc/en-us/articles/214767107-Forwarding-a-Squarespace-domain

As an alternative, you could just point the DNS to a Netlify or Cloudflare account and handle the redirection logic there instead.

![CleanShot 2024-07-28 at 07 37 46@2x](https://github.com/user-attachments/assets/10af0398-9ffc-4ae0-99a2-f2c74ab7b134)

**Comment by shiffman** [comment]
I've updated the Squarespace settings so this domain forwarding should be fixed in 24-72 hours. Will revisit and close when ready!

**Comment by fturmel** [comment]
Looks fixed, we can close this!
