### ISSUE TITLE
Thumbnail Images for Code Examples don't seem to work

### ISSUE THREAD

**Issue by dipamsen** [CodingTrain/thecodingtrain.com#168]
From https://github.com/CodingTrain/thecodingtrain.com/issues/68#issuecomment-1043285167, there is supposed to be "thumbnail images" for code examples like follows:

```jsonc
"codeExamples": [
  {
    "title": "Monty Hall",
    "description": "Three-door demonstration of the Monty Hall Problem with gameplay statistics",
    "image": "codeExample1.png",
    "urls": {
      "p5": "https://editor.p5js.org/codingtrain/sketches/pLW3_PNDM"
    }
  },
  // ...
]
```

## Actual Behaviour

- No thumbnail image showing up
  
   ![image](https://user-images.githubusercontent.com/59444569/172196133-4998bf8f-b210-45a6-826b-ae56c7eff864.png)

- It takes `codeExample1.png` image as the main thumbnail, instead of using `index.jpg`

   ![image](https://user-images.githubusercontent.com/59444569/172196394-9fdcf6ce-384b-4c8e-bad2-53466595ac8a.png)

(`codeExample1.png` contains test image, `index.jpg` contains actual video thumbnail)

**Comment by fdoflorenzano** [comment]
And how are the files located in the file structure?

**Comment by dipamsen** [comment]
I just assumed that all files are supposed to be in the root folder. Please lmk if they are supposed to be in a separate folder.

```
content/
  challenges/
    170-monty-hall-problem/
      index.jpg
      codeExample1.jpg
      index.json
```

**Comment by shiffman** [comment]
Ah, yes, investigating this a bit more it looks like the example images are supposed to go in a subfolder called `images`, you can see this here:

https://thecodingtrain.com/tracks/code-programming-with-p5-js/code/2-variables/4-random
https://github.com/CodingTrain/thecodingtrain.com/tree/main/content/videos/code/2-variables/4-random

Can you try that and see if it works? 

Also, we should add info about this to the site maintenance guide (if it's not already there!)

**Comment by dipamsen** [comment]
Thanks for the clarification.

Unfortunately, I still can't make the images work. 


File Structure:
```
content/
  challenges/
    170-monty-hall-problem/
      images/
        codeExample1.png
      index.json
```

Code:
```jsonc
"codeExamples": [
    {
      "title": "Monty Hall",
      "description": "Three-door demonstration of the Monty Hall Problem with gameplay statistics",
      "icon": "codeExample1.png",
      "urls": {
        "p5": "https://editor.p5js.org/codingtrain/sketches/pLW3_PNDM"
      }
    },
// ...
]
```

Output:
![image](https://user-images.githubusercontent.com/59444569/172228126-3daf9b5b-2c7d-4285-beba-519b31b896ca.png)

I also tried to use the exact same images and code as linked in the above comment (https://thecodingtrain.com/tracks/code-programming-with-p5-js/code/2-variables/4-random). It still doesn't work.

I am not completely sure whether this is a bug or something that I'm doing wrong.


----------

## Note

I tried to do the exact same thing inside the track (linked above) instead of Coding Challenge. All images seem to work in the track correctly. Maybe this has something to do with this feature only being available for tracks?

**Comment by dipamsen** [comment]
I am running the site locally using `dev`. I have tried `npm run clean`.

Here is a testing branch: https://github.com/dipamsen/thecodingtrain.com/tree/testing-playground

https://github.com/dipamsen/thecodingtrain.com/blob/6515a3b2fa167878e6adb0d68ff62522cc7940e0/content/videos/challenges/170-monty-hall-problem/index.json#L26 
https://github.com/dipamsen/thecodingtrain.com/tree/testing-playground/content/videos/challenges/170-monty-hall-problem

On running this branch locally (`npm run dev`), no thumbnail image is seen.

**Comment by fdoflorenzano** [comment]
Thank you so much. I think I found the issue, it's a little bug with the script that links all this things together. I'll post a fix in a PR soon.

**Comment by shiffman** [comment]
Yay, this is fixed! @dipamsen if you want to try adding yours back in and assuming it's all good we can close this!

**Comment by dipamsen** [comment]
Sure!

**Comment by dipamsen** [comment]
Sure!
