### ISSUE TITLE
Challenge paths seem inconsistent with other paths (pluralization)

### ISSUE THREAD

**Issue by lobertrand** [CodingTrain/thecodingtrain.com#169]
From looking around the website, this what paths look like : 

| Description | Example Path |
|---|---|
| Homepage | `/` |
| All Guides | `/guides` |
| Individual Guide | `/guides/getting-started` |
| All Tracks |  `/tracks` |
| Individual Track | `/tracks/code-programming-with-p5-js` |
| All Challenges | `/challenges` |
| Individual Challenge | `/challenge/170-monty-hall-problem` |

Shouldn't the path of individual challenges begin with `/challenges` instead of `/challenge` ?

**Comment by shiffman** [comment]
> Shouldn't the path of individual challenges begin with /challenges instead of /challenge

Ah, great question! I think I'm ok with it being "challenge" b/c it is a path for one challenge. That said it is a little confusing and maybe it makes more sense for "one challenge" to be a "subdirectory" of all "challenges". I'm open to changing it but we should decide soon b/c it affects all the internal links!

@fdoflorenzano is there any reason why it should stay the way it is?

**Comment by fdoflorenzano** [comment]
Hey! I did change it to singular for some reason back when I implemented pagination on the`/challenges` page, but I can't remember why that was. I can try reversing it back and test if there's any error by doing this, but I think it should be OK.

**Comment by shiffman** [comment]
> Hey! I did change it to singular for some reason back when I implemented pagination on the`/challenges` page, but I can't remember why that was. I can try reversing it back and test if there's any error by doing this, but I think it should be OK.

Sounds great, thank you @fdoflorenzano!
