### ISSUE TITLE
Maintain the Website Guide

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#173]
In #172 I removed content that still referenced the old website's markdown and YAML (hopefully I didn't delete anything that was still relevant?) We also have the Content Structure Guide!

https://github.com/CodingTrain/thecodingtrain.com/blob/main/content/pages/guides/content-structure-guide.md

Should this be a separate guide that is referenced by the maintenance guide? I think maybe it makes more sense to merge these two and bring all the useful info from the Content Structure Guide into the maintenance guide?

@klinegareth I know you might not see this for a while but feel free to weigh in with any thoughts!

@fdoflorenzano if you are able to do a quick scan over the [content structure guide](https://github.com/CodingTrain/thecodingtrain.com/blob/main/content/pages/guides/content-structure-guide.md
) and note anything that you've recently updated or changed that might be helpful!

**Comment by fdoflorenzano** [comment]
@shiffman I'll give it a look today, hopefully I'll have an update between today and tomorrow. If I see any relevant stuff to add to the Maintain the Website Guide, should I go ahead? (I'll be working on another branch of course)

**Comment by shiffman** [comment]
> @shiffman I'll give it a look today, hopefully I'll have an update between today and tomorrow. If I see any relevant stuff to add to the Maintain the Website Guide, should I go ahead? (I'll be working on another branch of course)

Yes please, any and all contributions / edits / updates to the guides are welcome! They are very much just "starter docs" and in progress now!

**Comment by klinegareth** [comment]
@shiffman I think the site maintenance guide is more or less a beginner-friendly version of the content structure guide, or at least that's how I've been thinking about it. It might be good to link to the content structure guide in the maintenance guide as a more detailed breakdown of how the site works for those interested!

**Comment by shiffman** [comment]
Thanks for the work on the site maintenance guide! We can open new issues as needed!
