### ISSUE TITLE
"The Coding Train" Footer Logo Being Cut Off.

### ISSUE THREAD

**Issue by coderpro1234-2** [CodingTrain/thecodingtrain.com#1759]
On all of the pages, the text that says "The Coding Train" in the footer is cut off at the word "Train". Instead of the width of the svg being 326px, it is 250px.

![Screenshot 2024-11-07 at 10-17-59 The Coding Train](https://github.com/user-attachments/assets/67bf9513-efad-4c64-a759-b2f246103c60)

![Screenshot 2024-11-07 101722](https://github.com/user-attachments/assets/42d0bc9f-a9a3-461d-aea8-e8ebfe37f3fc)

**Comment by fturmel** [comment]
Thanks for reporting this! I think it's my fault (#1745), strangely `svgo` removes the svg `viewBox` attribute by default - which is definitely not a safe operation for a minifier/optimizer to do. PR incoming.
