### ISSUE TITLE
Featured Coding Challenge

### ISSUE THREAD

**Issue by dipamsen** [CodingTrain/thecodingtrain.com#183]
In the about page, there is a featured section where a coding challenge is "featured".

![image](https://user-images.githubusercontent.com/59444569/172424800-748a96ce-7dc9-431a-a71a-f5abdcffaf56.png)

Is this supposed to always show the latest coding challenge?

If yes, it should be updated automatically (?). If no, the description incorrectly states the ASCII challenge as the 'latest coding challenge'.

**Comment by shiffman** [comment]
I decided to have this manually curated with the idea that it will almost always be the most recent one but it's not required. But you are right that the description should not say "latest"!
