### ISSUE TITLE
Discord Redirect

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#184]
The previous site had a redirect from https://thecodingtrain.com/discord to a permanent discord invite. What's the best way to add this back into this site? @fdoflorenzano feel free to let us know if there is a specific way you prefer we implement this! 

I'm also trying to remember what other redirects we might have had? I guess we'll discover them as they come up!

**Comment by fdoflorenzano** [comment]
I'm not sure which is the best way of doing this in Gatsby. It looks like it [can be added in the build process](https://www.gatsbyjs.com/docs/reference/config-files/actions/#createRedirect), but I would have to test it out with Netlify.

**Comment by M0nica** [comment]
There's also an option to use configure Netlify's redirects in `netlify.toml` or `_redirects` to handle redirecting pages. Although, the Gatsby approach would be hosting agnostic and would work locally unlike the Netlify approach. 

Documentation for the Netlify redirects approach:
- https://prince.dev/netlify-redirects
- https://docs.netlify.com/routing/redirects/

I've used the Netlify approach for my site [React Robins](https://www.reactrobins.com/) for the "Discord" and "Submit a Talk" links: https://github.com/React-Robins/website/blob/13f53379e0a17e990f6619af03529d24ec9bf362/static/_redirects.
