### ISSUE TITLE
Additional Context for Site Maintenance Guide

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#194]
Picking up with @skaser85's #192 

I'd love to add a short section about what generally needs to be updated and added, for example:

* Update links to code examples (p5 web editor for p5, new Coding Challenges repo for Processing)
* Add thumbnail images for code examples
* Remove broken showcase links
* Add thumbnail images for showcase
* Add additional metadata descriptions for related links and videos
* Replace any links to old website with new ones.

**Comment by skaser85** [comment]
@shiffman, some questions for clarification:

For the first item (Update links to code examples...), I'm taking that to mean that each of the p5 examples has a corresponding p5 web editor link that takes the user to the correct p5 web editor page, right?

Also for the first item, I'm not sure what you mean by the "new Coding Challenges repo for Processing".  I think I recall from the steam that you were wanting to create a new repo for the Processing Coding Challenges.  Has that been done?  If so, can you send me a link to it?  I looked through the Coding Train's repos, but nothing stuck out to me as being specifically for Processing .

**Comment by shiffman** [comment]
Hi @skaser85! Thank you again for helping with this, I appreciate it so much and am in awe of everyone's generous contributions! Here are some quick thoughts:

>  I'm taking that to mean that each of the p5 examples has a corresponding p5 web editor link that takes the user to the correct p5 web editor page, right?

That is correct! There might be some exceptions but 99% of them have a web editor link!

> Also for the first item, I'm not sure what you mean by the "new Coding Challenges repo for Processing". I think I recall from the steam that you were wanting to create a new repo for the Processing Coding Challenges. Has that been done? If so, can you send me a link to it? I looked through the Coding Train's repos, but nothing stuck out to me as being specifically for Processing.

The new repo which is still in progress is here!

https://github.com/CodingTrain/Coding-Challenges/

It's not necessarily for Processing examples only, it's just any Coding Challenge source code that does not fit into the p5 web editor or need an entirely separate GitHub repo (which ends up being Processing versions of the challenges for the most part.)

**Comment by shiffman** [comment]
Closing! Always more work to do on the site maintenance guide though of course, we can open new issues as neccessary!
