### ISSUE TITLE
Link icons cut off in Windows

### ISSUE THREAD

**Issue by dipamsen** [CodingTrain/thecodingtrain.com#215]
On Windows, the emojis are wider due to which the emoji appears cut off from the right.

![image](https://user-images.githubusercontent.com/59444569/172868093-986b8f8d-c268-4903-93d1-6faa5b3a4ce7.png)
Screenshot on Windows 10, Chrome 102.0.5005.63 (64-bit)

**Comment by shiffman** [comment]
tagging @fdoflorenzano to take a look at this one!

**Comment by shiffman** [comment]
I think this can be closed now! @dipamsen can you confirm?

**Comment by dipamsen** [comment]
Yes!
