### ISSUE TITLE
Redundant URL for Side Tracks

### ISSUE THREAD

**Issue by dipamsen** [CodingTrain/thecodingtrain.com#231]
The urls for side tracks are unnecessarily long and redundant:
```
https://thecodingtrain.com/tracks/p5-tips-and-tricks/tracks/side-tracks/p5-tips-and-tricks/github-pages-hosting
```

A better url would be 
```
https://thecodingtrain.com/tracks/side-tracks/p5-tips-and-tricks/github-pages-hosting
```

**Comment by shiffman** [comment]
Ah, yes, we discussed and simplified the best we could with #104 and #118 for the main tracks, @fdoflorenzano what would be possible for side tracks? Can we skip some of the duplication in the URL?

**Comment by shiffman** [comment]
Ah ok so that must be the issue, it should just be moved to:

```
content/videos/p5-tips-and-tricks
```

**Comment by dipamsen** [comment]
So, all main and side tracks files are to be placed in the `videos` folder in their own directory. These files are to be referenced in the track's `index.json` file.
The URL of a video in a main/side track is 
```
https://thecodingtrain.com/tracks/<track-name>/<track-directory-name>/<video-name>
```

Is this correct?

**Comment by shiffman** [comment]
> 

Yes, that looks right to me! I try to be concise with the directory names, like I think I used "noc" for "nature of code", etc. I suppose the directory path has some SEO value, but clarity and ease are also priorities.

@dipamsen feel free to move some things around if you have a suggestion!

**Comment by fdoflorenzano** [comment]
> ```
> https://thecodingtrain.com/tracks/<track-name>/<track-directory-name>/<video-directory-name>
> ```
> 
> 
>     
>   
> 
> Is this correct?

Just adding another confirmation that this is correct!
