### ISSUE TITLE
Incorrect Ordinal Number for Dates

### ISSUE THREAD

**Issue by dipamsen** [CodingTrain/thecodingtrain.com#247]
![image](https://user-images.githubusercontent.com/59444569/173193111-9fb3488a-1953-4878-9464-2479715ace76.png)
This should say Jun 11th 2022.

The code defaults to `st` when the date ends in 1, `nd` for 2 and `rd` for 3. 11, 12 and 13 are special cases which have to be accounted for.

**Comment by shiffman** [comment]
Great catch!
