### ISSUE TITLE
Site coding progress main issue

### ISSUE THREAD

**Issue by fdoflorenzano** [CodingTrain/thecodingtrain.com#25]
This issue serves as the main summary reference that holds a list of TO-DOs for big sections or pages in The Coding Train site. It also holds references to internal and external references that relate to the project.

## References
- Current [The Coding Train site](https://thecodingtrain.com/)
- Current [content repo for site](https://github.com/CodingTrain/website)
- [Wireframes Figma file](https://figma.com/file/azcNoPyLTkKDBtVjPMV9KC/Wireframes-(Round-2)?node-id=358%3A36671)
- [Data Taxonomy](https://figma.com/file/Eljq2bCrPqXfeLol8JjIyz/Taxonomy-(v2)?node-id=0%3A1)
- [Current visual designs](https://figma.com/file/9w2xIjSuArvHlLSrIVANvh/Visual-Design?node-id=399%3A5986)

## Language
_To be completed by Coding Train team_
- [x] #56 
- [x] #72 

## Content
_To be completed by Coding Train team_
- [x] #88 
- [x] #87 
- [ ] #128
- [ ] #131
- [x] #122 
- [x] #50 
- [x] #51 
- [x] #55 
- [x] #77
- [x] #92 
- [x] #79 
- [x] #80

## Pages
_To be completed by DSI team_
- [x] #44
- [x] #121 
- [x] #112 
- [x] #111
- [x] #84
- [x] #27
- [x] #29
- [x] #31
- [x] Create tag element in back-end for topics and languages
- [x] #26
- [x] #28 
- [x] #30
- [x] #109 
- [x] #76

## Other functionality
_To be completed by both DSI team and Coding train team_
- [x] #78
- [x] #85
- [x] #120 
- [x] Content structure guide for Coding Train Team
- [x] #61 
- [x] #57 
- [x] #63 
- [x] MD/MDX guide loading and page creation
- [x] #46 
- [x] Add share video functionality

## After launch
- #52 
- #69 
- Time of day changes on homepage scene
- Sorting tracks
- Sorting challenges
- Showing multiple featured challenges in challenges/
- Passenger Showcase/Contributions gallery
- #81 
- #86

**Comment by shiffman** [comment]
Hi @runemadsen @bravomartin and @fdoflorenzano! As you can see I'm going through all the issues and pull requests today for the website. Nothing here is urgent but I thought I would comment on some of the remaining items on the list here that @fdoflorenzano put together. I'm happy to this "summary" issue be closed and move to specific issue threads to discuss each item if that is preferable.

### Tracked in separate issues:
- [ ] #128
- [ ] #131

### Completed?
- [ ] #44

### For discussion (open new issue?)
> Time of day changes on homepage scene
This would be fun to do still! CT team could take it over if you prefer?

> Sorting tracks
Discuss in #417?

> Sorting challenges
Discuss in #283?

> Showing multiple featured challenges in challenges/
I don't feel this is necessary, but happy to discuss!

> Passenger Showcase/Contributions gallery
I would LOVE to have a dedicated showcase page for all submissions. How realistic is this to develop? Shall I open a new issue to discuss?

**Comment by bravomartin** [comment]
Agree. lets close this issue, and add a new issue for your last item: Creating a showcase page for all submissions.
The rest in your list seem to be reflected in other issues.

In general I think it would be great if CT team takes over, and we will be happy to provide support and help out as needed.
