### ISSUE TITLE
Related Challenges

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#262]
Noting that in #261 I removed "Related Challenges" (from tic-tac-toe for example) since the tests fail if we try to link to a challenge that is not on the site yet. When all the challenges have been ported, I'd welcome a pull request that does a pass over all of them to link up the related ones!

I'm forgetting, can we use the "related challenges" property in videos that are part of tracks also? @fdoflorenzano

**Comment by fdoflorenzano** [comment]
@shiffman Yes! You can with all types of videos.

**Comment by shiffman** [comment]
I believe this can be closed now that there are related challenges built out through all the content. @kfahn22 what do you think?

**Comment by kfahn22** [comment]
I think there might still be a couple without related challenges, but I think this can be closed.
