### ISSUE TITLE
Adding Tracks! (Main Tracks and Side Tracks)

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#279]
Thanks to everyone for your heroic efforts in porting the coding challenges! I'm not sure if we are keeping the spreadsheet in #155 up to date, but I thought I would open a new issue to track all of the "tracks" and "side tracks" that need porting over to the new website! 

If you are interested in working on any these, please reply in a comment and let me know if you have any questions! @klinegareth for the tracks that are on the site, can you let us know if there are "unfinished" elements that others can contribute to?

Main Tracks are specifically curated sequences of videos that follow a "syllabus" (generally one of my classes at NYU but not necessarily.)

Side Tracks is a place where you the viewer of the Coding Train can get creative! Is there a collection of videos that go together well that you'd want to be able to share via a single URL? You are welcome to propose and curate side tracks for the website! Open a new issue with your idea so I can approve it before you go through all the work to make the JSON files etc.! I've got a starter list below of probably what makes the most sense?

* Main Tracks
  * [X] Nature of Code
  * [X] Code! Programming with p5.js
  * [x] Git and GitHub for Poets
  * [x] Beginner's Guide to Machine Learning with ml5.js
  * [x] Working with Data and APIs in JavaScript
  * [ ] Learning Processing

* Side Tracks
  * [X] Workflow 
  * [X] Algorithmic Botany
  * [X] p5 Tips & Tricks 
  * [ ] Guest Tutorials + Guest Conductors (fold these all into one?)
  * [x] Coding in the Cabana (also add these to challenges but give them a special numbering?)
  * [x] Topics in Native JavaScript
  * [ ] Discord Bots
  * [ ] Twitter Bots
  * [x] Websockets and p5.js
  * [ ] Anything else from https://www.youtube.com/c/TheCodingTrain/playlists
  * [ ] Make up your own!

**Comment by dipamsen** [comment]
I'm working on "Working with Data and APIs in JavaScript" Main track!

**Comment by kfahn22** [comment]
I am happy to help with whatever is needed!  I have been working on the challenges (and have been indicating the ones that I have taken in the spreadsheet in #155), but if you think other areas are priorities I can focus on them instead.   I am waiting to open pull requests and am checking on image file size, but would appreciate exact criteria.    From the above, I can work on Coding in the Cabana.

**Comment by shiffman** [comment]
Thank you @dipamsen and @kfahn22! I don't have an opinion re: priority, you are probably right it makes sense to do the challenges first especially since a lot of side tracks could be collections of challenges? The main tracks I would definitely do first before the side tracks!

@kfahn22 you can see what I did in #280, right now I've decided to keep all showcase images to a maximum of 800px width. I'm looking at the dimensions rather than the file size though I'm not clear what actually matters in terms of the gatsby build. So let's make that the convention for now!

I'd like to include the Coding in the Cabana as both a challenge and a side track, they don't have a number maybe let's add a letter for "cabana" to their JSON filename? @runemadsen @fdoflorenzano will this cause any issues in terms of the build? I guess we'll find out! They can end up in the sorting of challenges by date.

```
c1-maurer-rose.json
c2-collatz-conjecture.json
c3-hilbert-curve.json
c4-worley-noise.json
```

**Comment by kfahn22** [comment]
I am assuming there were contributions for the Coding in the Cabana challenges, but I can't find them.  Can you provide me a link?

**Comment by shiffman** [comment]
Try seeing what is at https://codingtrain.github.io/website-archive/

Thank you!!

**Comment by klinegareth** [comment]
Awesome to see people helping with the site! 

I think for tracks that are on the site already, the main thing to do would be to add topics, languages, and timestamps to videos. I think everything already on the site is JavaScript, but if there are other libraries used in a video (e.g. ml5) I think it would make sense to go through and add them. Timestamps are pretty tedious and I've basically ignored them for videos being ported over, so working on those would be super helpful but low priority.

Excited to see what people come up with for new Side Tracks!

**Comment by fdoflorenzano** [comment]
> don't have a number maybe let's add a letter for "cabana" to their JSON filename? @runemadsen @fdoflorenzano will this cause any issues in terms of the build? I guess we'll find out! They can end up in the sorting of challenges by date.

The names in the files can be of any form, the build system doesn't expect the numbering prefix, that's for us. Although, the front-end will look for the `videoNumber` property from the JSON an if it's defined, it will show it with the title. Note that that property expects a string, so it can be more than just a number. This only happens with challenges, regular videos don't use that property btw.

**Comment by SilvestriStefano** [comment]
Hello,
I would like to help out if I can. I could start working on the main track Git & GitHub for Poets.

**Comment by SilvestriStefano** [comment]
great! 
I'll start working right away!

**Comment by kfahn22** [comment]
I was thinking of starting on the ML5 track.  Are you planning on updating the repository?

**Comment by anusha-exe** [comment]
If no one is already working on the last main track Learning Processing, I could do it. Please let me know if it's fine

**Comment by kfahn22** [comment]
Thank you @anusha-exe!  I think @shiffman wants to redo the Processing videos, so maybe hold off until we have confirmation about that.

**Comment by anusha-exe** [comment]
Right. Thanks, @kfahn22

**Comment by shiffman** [comment]
I am planning on doing a new Processing series, that said I don't mind having the original one documented on the website for posterity. (Also, as an experiment I'm going to see about doing the new one as a single video.)

**Comment by kaitabuchi314** [comment]
Programming from A to Z is missing.

**Comment by shiffman** [comment]
> Programming from A to Z is missing.

I'd be open to including it! Many of the videos are very out of date, but some of it does and could be nice to annotate and organize!

**Comment by shiffman** [comment]
I think this issue is perhaps no longer needed and we can file individual issues for updating or adding tracks, ok to close?

**Comment by kfahn22** [comment]
I think ok to close.
