### ISSUE TITLE
Finding Individual Challenges

### ISSUE THREAD

**Issue by DenisovichDev** [CodingTrain/thecodingtrain.com#283]
It seems like a lot of coding challenges are missing in the new website. Not sure if it's because there is still work to be done or something else.

Should mention that even for the ones that are there, the challenges are a bit hard to find.

Thanks

**Comment by shiffman** [comment]
> Should mention that even for the ones that are there, the challenges are a bit hard to find.

Can you elaborate on this in case there's something we can do to help with find-ability?

**Comment by DenisovichDev** [comment]
In the old website all the challenges were listed in a single page, so it was possible for someone to do a simple Find to get to a challenge. That's how I used to look them up, at least. But now that there is pegination, the Find is not possible. I have two things in mind that can solve this.

1. Maybe a search bar? Although that would take time to implement.
2. A way to sort the challenges, by the challenge ID, most or least number of contributions etc

Also, I have decided to start porting challenges for the new site. I have read the content structure guide (great documentation), is there anything else I need to know?

Thanks for your time!

**Comment by DenisovichDev** [comment]
Thanks! I will get to work.

**Comment by dipamsen** [comment]
I do agree on the issue of it being difficult to find challenges. Once all the challenges are ported, it will be quite tedious to 9 pages just to find the Game of Life challenge. A search bar would be extremely helpful for this purpose.

**Comment by shiffman** [comment]
> I do agree on the issue of it being difficult to find challenges. Once all the challenges are ported, it will be quite tedious to 9 pages just to find the Game of Life challenge. A search bar would be extremely helpful for this purpose.

@runemadsen @fdoflorenzano I realize this is perhaps a can of worms / out of scope of our original site plan, but I am also finding that I am spending a lot of time clicking around when looking for the page of a specific challenge. Let us know if you have any thoughts about this. Related to this is that the "topics" have ballooned into more free-form tags. I haven't been keeping a close eye on these, I wonder if we should rethink how they are used/displayed? 

😂 

<img width="522" alt="Screen Shot 2022-07-05 at 4 26 22 PM" src="https://user-images.githubusercontent.com/191758/177410470-aac87a25-7495-4f17-93f8-481916373fe7.png">

**Comment by runemadsen** [comment]
@shiffman I think a good first solution for the challenges is to bump up the number of challenges per page significantly. If we go from 10 per page to something like 30-50, it shouldn't be a problem with load times and it would cut down the number of pages a lot.

And yes, that topic selector doesn't work for this many topics. Let me just speak to the team and get back to you!

**Comment by shiffman** [comment]
Noting #401 as related to discussion here. I wonder if we always add the challenge name as a "topic" then we essentially have this "search" feature? Or are there unintended consequences to this idea that I'm not thinking of. . ?

**Comment by DenisovichDev** [comment]
What if apart from the "topic" property, we store the possible search keywords in a different property. And since there would be no frontend of this list of search keywords, we can focus less on its looks and more on its functions.

**Comment by shiffman** [comment]
@allcontributors add @DenisovichDev for content and ideas

**Comment by shiffman** [comment]
Noting that in #529 I changed the pagination from 10 to 50. This, I hope, will contribute to improving find-ability for coding challenges.
