### ISSUE TITLE
Passenger Showcase submission form

### ISSUE THREAD

**Issue by kfahn22** [CodingTrain/thecodingtrain.com#308]
The form is a really great addition!  Maybe the problem is everyone is trying to use it at once??
Here are the issues I ran into.  
1.  The constraint on imp.png (rightly so!) is with size as well as width.  An image can be meet the 800px size requirement as still be above size limit.  Once you have an image that violates the rule, there does not appear to be a way to replace with one that meets requirements.  
2. I tried submitting without a link to a website and it says website is required.  Even with everything correct, it says there is a problem with the data.
<img width="543" alt="website" src="https://user-images.githubusercontent.com/65121394/177051911-98fa3db1-4de6-4e46-b6f4-ecdc86a87067.png">
<img width="394" alt="data" src="https://user-images.githubusercontent.com/65121394/177051915-6443837f-b255-4b97-a72f-b8b492f1a5aa.png">

**Comment by shiffman** [comment]
Thanks @kfahn22!!! Can you drop the image that failed into Discord? I'll take a look. Tagging @runemadsen too to review your feedback!

Should we make "Your Website" optional?

**Comment by kfahn22** [comment]
Personally, I think website should be optional  given that you try to be "beginner friendly."   I also think you should add that the image should be below  a maximum size constraint, if exceeding the limit causes the submission to fail.

**Comment by kfahn22** [comment]
Also wondering if email should be included as a field on the contribution.json form?

**Comment by shiffman** [comment]
Having a "website" link as optional works for me, I can imagine someone just wanting to submit their  p5 web editor sketch and only that. I believe the email is required in order to tie the pull request to a GitHub account? It is perhaps an issue to have so many people's email addresses sitting in the JSON files. I didn't think of this now, can we ask for github username perhaps? Or if people leave it out just assign the commits to the ChooChoo github account? @runemadsen what do you think?

**Comment by kfahn22** [comment]
--I have a concern at this point  that there are hundreds of showcase submissions up on the website, and a lot of them have different json files.  Is this going to be a problem at some point?
-- I agree, I don't think it is a good idea to have anyone's personal email in the json file (especially since this is a public repository.)  Having a default Github account makes sense to me.  At least if the goal is to make the process user friendly.

**Comment by shiffman** [comment]
> I agree, I don't think it is a good idea to have anyone's personal email in the json file (especially since this is a public repository.) Having a default Github account makes sense to me. At least if the goal is to make the process user friendly.

I was confused the email does not get saved to the JSON it's just for the git commit. I'm happy to keep this as optional and use the CT github account if someone doesn't want to enter theirs. But many will in order to have their account tied to their commit! I'll wait until @runemadsen weighs in before doing anything more!

**Comment by kfahn22** [comment]
The form just asks for an email, but doesn't mention GitHub.  Is the purpose to let the submitter know the status of their submission?

**Comment by runemadsen** [comment]
Thanks for this @kfahn22. See answers below:

> Should we make "Your Website" optional?
Yes, we can definitely make the website field optional

> Also wondering if email should be included as a field on the contribution.json form?
As @shiffman says, we're currently using the email field for the Git commit. In this sense, it's no different than if the users were submitting the PR's on their own. If we leave out the email field, it'll just be the choochoo account that did the commit, which is fine by me. 

> Once you have an image that violates the rule, there does not appear to be a way to replace with one that meets requirements.
I'm not sure exactly what you mean with this. Were you unable to select another image after seeing the error message?

> Even with everything correct, it says there is a problem with the data.
If you could share the image you tried to upload, that would be great. I doubt that it's related to many people using the form, so it's probably something about the image.

Thanks!

**Comment by kfahn22** [comment]
The thing that tripped me up yesterday was I assumed I would need to delete the original image before inserting the edited image.  I see now that if I just click choose image again it will over-right the original.  I am not sure what I was doing--maybe trying to drag it in??  The image I uploaded was 800px, but I didn't think to check file size until I got the error and then saw that it was still 1.3 MB.  I have done a ton of these by now, and that ones that are very colorful are still pretty large at 800px (at least with png).  l will investigate TinyPNG which was suggested by David.  I have shared the image on Discord, but for reference here is another similar one.   I have edited it to be 800px but it is still 1.6MB.  I am not sure why I wasn't able to submit with everything correct.  I had edited the image down to a low res, so that was no longer the issue.  I think it is a very good idea to have a limit on file size, but my suggestion is to make it clearer what the requirements are and also maybe suggest jpeg or compression for very colorful images.  
<img width="400" alt="julia2" src="https://user-images.githubusercontent.com/65121394/177153719-5b3da156-6df1-4fe8-aba5-9b8ef9f1456c.png">

**Comment by runemadsen** [comment]
Great, thanks @kfahn22! I'll add some better language around JPG uploads. If you use a tool such as https://tinypng.com/, this image can come down to around 400kb, but JPG will probably be better anyway.

**Comment by kfahn22** [comment]
I am working on  MacBook and the default for screen shots is PNG which is why I have used that format.  I think I made  sure the latest contributions I added were under 1MB and 800px.  I think my image failed because it was over 500kb, is that correct?  I am asking because some of the contributions probably exceed that limit.    Do I need to fix those?  (Most are fine, it is just the really colorful ones that are the issue.).  Also, Is there a way to convert pngs efficiently to jpg?

**Comment by shiffman** [comment]
Thanks @runemadsen and @kfahn22! Thinking through all of the above, here is my quick list of to do's for the passenger showcase:

* [ ] Add language around JPG uploads (can we add an error message specific to the image upload failing also?)
* [ ] Change "your website" to optional field
* [ ] Change "email" to optional field (maybe add note to explain we do not save the email, it is to tie the submission to a git commit?)

@runemadsen let us know if you want to take care of these or if we should take over from now on!

Also:
* [ ] Rework the pull request subject and comment text to have more information. (I wonder if we can easily embed the image for a quick preview?)

**Comment by kfahn22** [comment]
I did get an error message saying my image exceeded the file size (my memory on this is fuzzy)-- I think it was 500kb?

**Comment by runemadsen** [comment]
@shiffman I'll take care of this tomorrow!

**Comment by shiffman** [comment]
I'm going to close this issue now that the main points of discussion are resolved. We can track the `500` error and other enhancements in separate issues. (I'll open a new one right now for my comment above.)
