### ISSUE TITLE
Coding Challenge 154: Tic Tac Toe Minimax

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#343]
Challenge 154 is one of the most viewed challenges on the old site so it would be nice to port this one next!  (See #155).

Reply to this issue if you are interested in taking this one on!

**Comment by KobeLiesenborgs** [comment]
I'll take this one on!

**Comment by shiffman** [comment]
Thank you @KobeLiesenborgs for adding this! Leaving this issue open to track:

* [ ] timecodes
* [ ] showcase submissions
