### ISSUE TITLE
Newline Character does not work in description texts

### ISSUE THREAD

**Issue by dipamsen** [CodingTrain/thecodingtrain.com#352]
Adding `\n` characters in descriptions (video/track) does not show up as line breaks in the website. Is this intentional?

```jsonc
{
// ...
  "description": "In this video, I outline what you need setup and ready before you begin the course Working with Data and APIs in JavaScript.\n\nWhat you need to know:\n- JavaScript\n- HTML basics\n- Basics of CSS (useful but not required)\n\nMaterials/Programs:\n- Code editor (I use Visual Studio Code but other examples are included below)\n- Shell access to your computer (we go over this in Module 2)",
// ...
}
```

![image](https://user-images.githubusercontent.com/59444569/178030675-c00b427a-af13-4761-bdfb-79146fd70dc9.png)

**Comment by shiffman** [comment]
Hi @dipamsen! The descriptions aren't meant to be long and include outlines, etc. (even if some of the old content does). I think what makes more sense it to edit the description down to a few sentences and add additional information in the `groupLinks` or `timecodes`. That said, I'm not opposed to supporting line breaks if that is an easy fix! @fdoflorenzano @runemadsen what do you think?

**Comment by runemadsen** [comment]
I would vote for what @shiffman is describing: keeping the descriptions rather short and in a single paragraph. I think it's a nicer experience if all the videos follow the same formula.

**Comment by shiffman** [comment]
@dipamsen let us know if you think this is workable and feel free to tag me in a pull request on a specific video with a long description and I can rewrite it (though you are welcome to take a stab yourself of course!). If all seems good please close!

**Comment by dipamsen** [comment]
Thanks for the clarification! It was only this setup video (data and APIs 0.2) which had a multiline description. I have removed the extra part ("what you need to know/materials and programs") as that is highlighted in the video itself, and in the reference links as well.

**Comment by shiffman** [comment]
Thanks @dipamsen!
