### ISSUE TITLE
Starfield Coding Challenge

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#353]
I'm going to merge #152 which I created during a previous live stream demo of the website. Noting that the challenge still needs:

* [x] showcase images
* [x] code example images
* [x] main thumbnail image
* [x] timecodes
* [x] additional references/links
* [x] any other cleanup

**Comment by kfahn22** [comment]
I will take care of this.

**Comment by shiffman** [comment]
Thank you for taking case of this @kfahn22!!!
