### ISSUE TITLE
Code! track examples

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#364]
Filing this issue as a reminder to add links to the p5 web editor versions of the code demonstrated in the Code! track. I'd like to make sure this is done by start of school in September. Not sure if these are all easily findable in the `codingtrain` p5 web editor account or if I need to re-create these.

**Comment by dipamsen** [comment]
I would like to work on this! I am starting by scraping the examples data from the old website.

**Comment by shiffman** [comment]
@dipamsen can this be closed or is there more work to be done? Thank you for all the work you put into this!!!!

**Comment by dipamsen** [comment]
This can be closed!

**Comment by shiffman** [comment]
Ok, I'll open a new issue to track this list!
