### ISSUE TITLE
Missing Showcase Projects

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#367]
I'm opening an issue to track the discussion in #366 and #350. Some passenger showcase projects do not appear on the website after a successful build. My working theory is that there is some caching issue in the build process. I believe an `npm run clean` before `npm run build` resolves the issue. However, I'm not sure it makes sense to add `npm run clean` to each and every netlify deployment. 

@runemadsen I'll see what I can investigate this week and we can return to looking at this next week when you are available.

**Comment by shiffman** [comment]
Noting that last night when no other builds were running I ran a force "clear cache and deploy site."

<img width="536" alt="Screen Shot 2022-07-13 at 9 01 03 AM" src="https://user-images.githubusercontent.com/191758/178739645-87fb5221-72c1-447d-8f9d-f7add23d83d8.png">

The build took a ~67 minutes, but the missing showcase projects do now appear on the site. I may be mistaken but we should keep a close eye on these pages as I believe when this occurred before later deployments caused the projects go go missing again. We'll see if that happens this time.

<img width="323" alt="Screen Shot 2022-07-13 at 8 58 55 AM" src="https://user-images.githubusercontent.com/191758/178739254-53664c55-b9ac-46d4-976c-abc947087faa.png">

Tagging @kfahn22 and @alin256 in case you want to double-check your submissions.

**Comment by alin256** [comment]
The submissions showed up now, but I sent in 2 due to confusion. I can PR later to remove one.

@shiffman, I wonder if 172 should show up on the front page as the latest challenge? 
I did not figure out the gatsby layout, and I do not know if it is desired behaviour.

**Comment by dipamsen** [comment]
@alin256 the challenges featured on the home page are not dynamic, they need to be manually updated in [this file](https://github.com/CodingTrain/thecodingtrain.com/blob/main/content/pages/homepage/index.json)

**Comment by shiffman** [comment]
Unfortunately, after merging pull request #369 the showcase projects referenced here are missing again ([direct link to deployment in case its helpful](https://app.netlify.com/teams/shiffman/builds/62d0152ab9d3cd0008ec6d2b)). I'm going to run `clear cache and retry deploy`. I suspect there is something going on with the cache that persists even across later builds where the cache isn't cleared? Is that possible? [new build for tracking purposes](https://app.netlify.com/sites/codingtrain/deploys/62d0cd763e0408341b0180b4).

**Comment by shiffman** [comment]
As expected the projects returned after running `clear cache and retry deploy`.

**Comment by LemurDaniel** [comment]
Some older Submissions that worked on the previous webiste, don't show up either anymore:
[here](https://thecodingtrain.com/tracks/the-nature-of-code-2/noc/4-particles/3-particle-inheritance)

even though they are in the repo as contributions:
[here](https://github.com/CodingTrain/thecodingtrain.com/tree/main/content/videos/noc/4-particles/2-particle-emitters/showcase)

Some do work though:
[here](https://thecodingtrain.com/tracks/the-nature-of-code-2/noc/3-angles/1-angles-and-rotation)

**Comment by kfahn22** [comment]
The latest submissions are missing again.  Did this start with @alin256?  Was there a change in the build process that could account for this?  Very weird!

**Comment by dipamsen** [comment]
> Some older Submissions that worked on the previous webiste, don't show up either anymore:
> [here](https://thecodingtrain.com/tracks/the-nature-of-code-2/noc/4-particles/2-particle-emitters)
> 
> even though they are in the repo as contributions:
> [here](https://github.com/CodingTrain/thecodingtrain.com/tree/main/content/videos/noc/4-particles/2-particle-emitters/showcase)

This is because [this specific video](https://github.com/CodingTrain/thecodingtrain.com/tree/main/content/videos/noc/4-particles/2-particle-emitters/index.json) does not have the `canContribute` property, which is required to have a passenger showcase.

**Comment by runemadsen** [comment]
Thanks! I'm taking a good look at the build pipeline starting now. It'll take me a few days to go through it all, but my plan is to find ways to significantly decrease the build time and fix whatever build errors (including this one) that exists. I'll report back as soon as I have an update.

**Comment by shiffman** [comment]
@runemadsen has done some incredible work in #385! I'm hoping that this issue is resolved with all the updates and fixes to the build process, but I'm going to leave it open so that we can track it over the course this week as we merge new showcase submissions and pages. If you are able please check your submissions periodically and let us know!

**Comment by shiffman** [comment]
Do we know if this problem is resolved after all the updates to the build process? I haven't seen it return but also have not been checking super closely.

**Comment by runemadsen** [comment]
I feel like it's solved, so I'm happy to close this and have it reopened if the issue resurfaces. I believe it was caused by duplicated page generation.

**Comment by shiffman** [comment]
Great! Agreed!
