### ISSUE TITLE
Uniformity of challenge index images

### ISSUE THREAD

**Issue by kfahn22** [CodingTrain/thecodingtrain.com#387]
There are currently four major categories of index images for the challenges:
--older  black and white code image with Dan
--newer color code image with Dan
--black and white code image no Dan
--color code image no Dan

Should there be just one image type, and if so, which one should be picked?  There is a secondary issue that a lot of the code examples have a square canvas, but the index images on the website have a 16:9 aspect ratio, so some of the index images are cropped in an awkward way.

**Comment by shiffman** [comment]
Thanks for bringing this up! For the newest coding challenges my thinking is to include a version of the YT thumbnail that does not include the title text, for example:

![CC-168-MandelBulb_2 copy](https://user-images.githubusercontent.com/191758/179636904-c8f8b604-7697-48b8-ad25-aad27ed0dfff.jpg) ![CC-171-WaveFunctionAlt](https://user-images.githubusercontent.com/191758/179636906-105bd64b-95b7-457e-80a5-d336a776a62d.jpg)

So in terms of your list I'm inclined to go with "newer color code image with Dan", however it involves a bit of work / photoshop to do this for older videos so I think it's ok if the older challenges do not include me in the image. I'm also 100% fine with not including me and just having them be images of the visual output! Maybe that would be better? 

I'll bring this up in our discussions with DSI!

**Comment by shiffman** [comment]
After some further discussion, I think we should try colorful visual images of the challenge itself without me in the image! I think my face is all over the website plenty and what should be emphasized for a viewer looking for a challenge to try is the content of that challenge itself. We should keep them colorful when possible and themed with the CT colors.

https://coding-train-colors.vercel.app/

I'll try to block out some time to make a whole bunch of these (maybe a Twitch stream to work on the site even?) but @kfahn22 the ones you've made are terrific so feel free to create more if you like!

**Comment by kfahn22** [comment]
I would like to work on this!

**Comment by shiffman** [comment]
This is a helpful image too thanks @jasontheillustrator!

![image](https://user-images.githubusercontent.com/191758/180501432-4d66c334-64d3-42fb-a44e-e0fcbf795bcd.png)

**Comment by kfahn22** [comment]
I am running into an issue.  I am deleting the existing images and uploading new ones, but when I go to double check that the new ones are there I find the old ones instead.  Even more bizarre, it takes an increasing number to tries to get the new one in place??   I decided to document this behavior for toothpicks which I was replacing to get the right aspect ratio and Coding Train colors.  Do you have any idea what is going on?
![image_deleted](https://user-images.githubusercontent.com/65121394/180608550-8b2f8d4d-6f23-4ffa-9ca8-ec3977e68619.jpg)
![image_not_deleted](https://user-images.githubusercontent.com/65121394/180608556-58c36be1-a53e-4d92-a667-ad784d6dfbc1.jpg)
.

**Comment by kfahn22** [comment]
The second image shows the original image still there.

**Comment by kfahn22** [comment]
Sorry, it  just occurred to me that this is probably (I hope) a timing issue that I am just checking to soon.

**Comment by shiffman** [comment]
Hi @kfahn22, did you resolve this?

**Comment by kfahn22** [comment]
Yes, I was just being too impatient!  I used to be able to check immediately and the changes would be there, but I guess at this point that is no longer true.  (I was double checking before adding next one b/c  I have to save to desktop to get the jpg file format and images all have same name.)

**Comment by shiffman** [comment]
I'm going to close this issue now that most of the images have been updated according to the new style guidelines. we can open any specific issues or chat on Discord about specific challenge images.
