### ISSUE TITLE
Showing "0 matches found" even when filter is off

### ISSUE THREAD

**Issue by dipamsen** [CodingTrain/thecodingtrain.com#397]
![image](https://user-images.githubusercontent.com/59444569/180831662-e4bb5798-9a5e-4267-a8c3-5d9778b905bd.png)
Shows message "0 videos within this track match the tag:" when no topics/languages are selected.

**Comment by shiffman** [comment]
Tagging @runemadsen as perhaps this bug relates to our discussion about topics/search in #283.

**Comment by dipamsen** [comment]
I believe this is originated due to change in URL structure in #385

**Comment by runemadsen** [comment]
Yes, this is an error that we can fix on our end!
