### ISSUE TITLE
Order of Tracks

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#417]
I'm curious about how the order of tracks is set on https://thecodingtrain.com/tracks? Is it most recently updated? Random? By date?

I think I might like to manually set the order in a JSON file. What do you think @runemadsen?

**Comment by runemadsen** [comment]
Good question. [This is the code we use to load tracks](https://github.com/CodingTrain/thecodingtrain.com/blob/main/src/templates/tracks.js#L83-L89) and there is no sort. So I'm guessing it's defaulting to the order in which the nodes were created? It's very easy to add a sort based on a field, and it can be date or just a number you can set to curate the order. Any preference?

**Comment by shiffman** [comment]
I think to start let's add a "sort order" number so I can curate. I can always change it to something else later.

**Comment by runemadsen** [comment]
Great, will do

**Comment by kfahn22** [comment]
I think it would be useful for the tracks to be subdivided into MAIN and SIDE.  It isn't obvious when you look at the page that MAIN tracks are listed first and then SIDE tracks.   As for sorting, my vote would be alphabetical (after the featured track in each subcategory.)

**Comment by dipamsen** [comment]
For ordering, I think it might be cleaner to have a `tracks.json` file somewhere listing the track slugs in order; and import it and sort the tracks accordingly?

**Comment by shiffman** [comment]
This is ready to go! Open to any suggestions on the best order!
