### ISSUE TITLE
Finishing Touches on Code! Track

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#419]
This list comes from #364, thank you @dipamsen!

- [x] Code Examples
- [x] Code Example Images
- [x] Passenger Showcase
- [x] Passenger Showcase Images
- [x] Timestamps 
- [ ] Review/add missing References

**Comment by kfahn22** [comment]
I will work on adding images.

**Comment by kfahn22** [comment]
I will work on timestamps.

**Comment by kfahn22** [comment]
Unless you want additional references I think this is completed.

**Comment by shiffman** [comment]
Amazing, thank you @kfahn22! I'm going to browse through all of the pages for Code! and then close this issue!

**Comment by shiffman** [comment]
This is looking great! Closing for now and we can open new issues as needed!
