### ISSUE TITLE
Nicely integrating multi-part coding challenges with minimal changes

### ISSUE THREAD

**Issue by lobertrand** [CodingTrain/thecodingtrain.com#420]
## Suggestion

Two elements that I think should really be available on a multi-part challenge page are the *n* videos and their corresponding timestamps. To accomplish that, I suggest the following solution:

- We could add an optional array field `nextParts` to the `index.json` file of multi-part coding challenges, which would allow us to indicate the `videoId` and `timestamps` of the next parts of the challenge.
- The root `videoId`, `date` and `timestamps` fields of `index.json` would refer to the first part/video of the coding challenge.
- All the other fields (`title`, `description`, `videoNumber`, ..., `codeExamples`, `groupLinks`) and the passenger showcases would still be related to the "global" challenge, not to a specific part.

### Configuration example

`content/videos/challenges/54-islamic-tiling-patterns/index.json`
```json
{
  "title": "Islamic Star Patterns",
  "description": "In this bonus super-sized coding challenge, I work through visualizing Islamic Star Patterns in p5.js.",
  "videoNumber": "54", // not "54.1"
  "videoId": "sJ6pMLp_IaI", // videoId of 1st part
  "date": "2017-02-14", // date of 1st part
  "languages": [...],
  "topics": [...],
  "canContribute": true,
  "relatedChallenges": [],
  "timestamps": [ /* timestamps of 1st part */ ],
  // New field
  "nextParts": [
    {
      "videoId": "lobJ9gzbLo8", // videoId of 2nd part
      "timestamps": [ /* timestamps of 2nd part */ ]
    },
    {
      "videoId": "qg8LDsd57gF", // videoId of 3rd part
      "timestamps": [ /* timestamps of 3rd part */ ]
    }
  ],
  "codeExamples": [...],
  "groupLinks": [
    {
      "title": "References",
      "links": [...]
    }
  ]
}
```
*Note: this is a fictitious example, in reality challenge 54 has only 2 parts, not 3.*

### Design example

![wireframe](https://user-images.githubusercontent.com/37326143/182874837-00fc165e-3086-457a-9f79-f77be41a38f7.png)

- Clicking on a part number would switch the player to the corresponding video and display the associated timestamps.
- This "parts pagination" would not appear for single part coding challenges.

### Temporary solution

Whether or not we decide to implement this strategy, I think it would still be beneficial to normalize and document the *(temporary)* way that contributors should port multi-part challenges to the new website. This could be included in the "Maintaining the website" guide.

Such intermediate solution could be to :
- create a single folder per challenge (not per part) ;
- fill in the `videoId` and `timestamps` for the first video ;
- link to the next parts as YT videos in a `groupLinks` titled `Next Parts of this Challenge` ;
- combine code examples, passenger showcases and link references from all parts of the challenge.

Then we would just have to add a `nextParts` field if my solution were to be implemented.

**Comment by lobertrand** [comment]
## Previous mentions of the multi-part challenges problem

### https://github.com/CodingTrain/thecodingtrain.com/pull/363#issuecomment-1180383339

> `@shiffman` :
> So the old site had a system for multi-part coding challenges but I've now moved to just releasing longer videos with chapters. I'm not sure the best way to handle these for the older ones. I think let's just put the contributions in the last part? Maybe then we put canContribute: false in the first part? And a note in the description that says contributions are in part 2? And make sure all the parts are linked via "related challenges" or a "group link"? I think this is better than duplicating them. @klinegareth what do you think?

### https://github.com/CodingTrain/thecodingtrain.com/pull/363#issuecomment-1180409023

> `@shiffman` :
> Here's a new idea. For older multi-part challenges just have one page for them that's associated with the first (last?) video. Then create a grouplink with the other parts. We could also make a side track for some of the more popular ones.

> I think we can bandaid this b/c I'm not doing multi-part challenges anymore and there aren't that man

**Comment by lobertrand** [comment]
> Hi @lobertrand! This is a fantastic idea! As I mentioned in earlier threads, it's lower priority b/c I don't necessarily plan on doing multi-part challenges in the future, but some previous ones are still quite popular and having a way of handling them elegantly would be nice. Are you interested in working on the implementation for this? I'm happy to approve it but I'd be curious for any design feedback from @bravomartin and/or @runemadsen before finalizing a plan.
> 
> Thank you!!!!

Hi @shiffman! I'd be happy to work on the implementation for this. Any feedback on this idea and/or on the graphic design aspects is welcomed :smiley: . The image I created is more of a wireframe than a final design and could certainly be improved for accessibility and to fit with the overall design system.

**Comment by kfahn22** [comment]
I really like this idea, too!   It would be nice if there was a way to add the timestamps for the additional parts to the challenge, which is one drawback to current implementation.

**Comment by lobertrand** [comment]
I created a working demo of this on PR #428 
Deploy preview is here : https://deploy-preview-428--codingtrain.netlify.app/challenges/54-islamic-star-patterns

**Comment by shiffman** [comment]
WOW! This is amazing! It's so good I might even consider doing multi-part coding challenge again 😂 

@runemadsen is currently away but when he is back, he can review the design.

@allcontributors please add @lobertrand for code and content.

**Comment by lobertrand** [comment]
I was thinking that maybe it would be better to have all the parts in an array in the JSON file (instead of just the next parts) 🤔 
```json
{
  "title": "Islamic Star Patterns",
  "description": "In this bonus super-sized coding challenge, I work through visualizing Islamic Star Patterns in p5.js.",
  "videoNumber": "54",
  "videoId": "sJ6pMLp_IaI", // ignored if "parts" array is not empty
  "date": "2017-02-14",
  "languages": [...],
  "topics": [...],
  "canContribute": true,
  "relatedChallenges": [],
  "timestamps": [...],  // ignored if "parts" array is not empty
  // New field, only used for multi-part challenges
  "parts": [
    {
      // 1st part info
      "videoId": "sJ6pMLp_IaI",
      "timestamps": [...]
    },
    {
      // 2nd part info
      "videoId": "lobJ9gzbLo8",
      "timestamps": [...]
    }
  ],
  "codeExamples": [...],
  "groupLinks": [
    {
      "title": "References",
      "links": [...]
    }
  ]
}
```
Then it would allow us to add other properties/metadata for each part more easily in the future if we want it (like a specific title for each part for example).
What do you think? 😃 @shiffman  @kfahn22

**Comment by kfahn22** [comment]
When I ported Islamic star and Chaos, I had to combine elements from both parts--the code examples for parts 1 & 2, references, and videos.  This would allow for those elements to be separated, which might be nice.  As long as this has no effect on the other single part challenges, I think it is  a good idea.

**Comment by dipamsen** [comment]
If we are going for separating all elements for the different parts (`codeExamples`, `groupLinks`, etc), then different url paths for the parts might be worth considering. 
Something like `/2` or `/p2` could be used so that each part had its own URL.

**Comment by runemadsen** [comment]
Hi all! Just catching up on this. I think this is great! My only concern is that we're adding another navigational element that looks very different from the track navigation but it actually serves the same purpose. Another way to implement the same idea is that show the different challenge videos like we do with the tracks:

<img width="445" alt="Screen Shot 2022-08-15 at 9 06 47 AM" src="https://user-images.githubusercontent.com/192021/184591244-29ceebfe-4995-4295-986a-8cef2584edf0.png">

If this is something that is just needed for a few videos, I'm more than fine just using the current design, but I would maybe vote for simplifying it so all things with multiple videos look the same. The JSON could also take inspiration from the track JSON, so it's more streamlined. 

Thoughts on this?

**Comment by lobertrand** [comment]
@runemadsen I totally agree with you on this, it would be better to reuse the existing component for navigating through sequential videos, just like in tracks.

I'm gonna work on a solution using this and with the challenge parts placed in a subfolder, referenced in the main JSON file, this should give us URLs for the parts for free. Does it sound good to you? :)

My only concern is that this diverges too much from the way single part coding challenges are handled, but I'm gonna try to make it work :)

**Comment by kfahn22** [comment]
ml5 has a couple of chapters with just a single video, so I think integrating with single part challenges is doable.  

My concern is with the showcase folder.  The original approach of combining parts was a bandaid to avoid having duplicate showcase folders on site.  Maybe language could be added in the intro stating where the showcase will reside (first or last part)?

**Comment by shiffman** [comment]
Thanks for your feedback @runemadsen! @kfahn22 I agree. @lobertrand I think a priority for this feature is to keep one single video folder for a multi-part challenge and only one listing on the main challenge page. . but you can bounce between the parts (potentially with their own timecodes?) one the video page itself. I think the code examples and reference links can also be the same for all parts. To clarify:

- CHALLENGE DATA
   - videoid: **array of ids?**
   - time codes: **array of timecodes?**
   - topics, languages: one listing for all parts
   - code examples: one listing for all parts
   - reference links: one listing for all parts
   - showcase: one listing for all parts
   - etc.

**Comment by lobertrand** [comment]
@runemadsen I implemented a design that's more in line with the design of tracks, but kept the JSON the same, to follow what @shiffman said : 
#428 : https://deploy-preview-428--codingtrain.netlify.app/challenges/54-islamic-star-patterns

![image](https://user-images.githubusercontent.com/37326143/185246703-9ae54768-f17e-4182-93ef-e735696459aa.png)

@shiffman I think it's not possible for a GraphQL field to allow multiple types at a time (`string` and array of `string`s for example) and we would have to convert all the existing `videoId`s to arrays if we wanted to allow multiple values for them. The way I configured the JSON for now is the following : 

```json
{
  "title": "Traveling Salesperson", // challenge title
  "description": "...",
  "videoNumber": "35",
  "videoId": "BAejnwN4Ccw", // ignored if "parts" is not empty
  "date": "2016-08-24",
  "languages": ["p5.js"],
  "topics": ["traveling salesperson", "permutation", "..."],
  "canContribute": true,
  "relatedChallenges": [],
  "timestamps": [], // ignored if "parts" is not empty
  "parts": [
    {
      "title": "Part 1: Traveling Salesperson (TSP)",
      "videoId": "BAejnwN4Ccw",
      "timestamps": [{ "time": "00:00", "title": "..." }]
    },
    {
      "title": "Part 2: Lexicographic Order",
      "videoId": "goUlyp4rwiU",
      "timestamps": [{ "time": "00:00", "title": "..." }]
    },
    {
      "title": "Part 3: TSP with Lexicographic Order",
      "videoId": "9Xy-LMAfglE",
      "timestamps": [{ "time": "00:00", "title": "..." }]
    }
  ],
  "codeExamples": [...],
  "groupLinks": [...]
}
```

The only fields which are related to a specific part are `parts.title`, `parts.videoId` and `parts.timestamps`. The topics, languages, date, description, relatedChallenges, code examples, reference links only have one listing for all parts.

**Comment by shiffman** [comment]
This looks amazing! @runemadsen if it looks good to you I'll go ahead and merge. It's so good I almost want to do more multi-part challenges now!
