### ISSUE TITLE
Showcase cover images do not work in tracks

### ISSUE THREAD

**Issue by dipamsen** [CodingTrain/thecodingtrain.com#434]
Cover images for showcase submissions do not appear on the website. It uses the placeholder image, even though an image with the same name as the json file is defined.

<details>
<summary>Examples</summary>

* [NOC 3.1 - Angles and Rotation](https://thecodingtrain.com/tracks/the-nature-of-code-2/noc/3-angles/1-angles-and-rotation) 
![image](https://user-images.githubusercontent.com/59444569/183851385-6200b95d-1ac6-43b2-afdc-b6b2aa9f5af4.png)
![image](https://user-images.githubusercontent.com/59444569/183851543-6351351f-1e62-484f-a5ef-d222f8e5e473.png)

* [Data and APIs 3.5 - Web Application Deployment](https://thecodingtrain.com/tracks/data-and-apis-in-javascript/data/3-the-weather-here/5-web-application-deployment)
![image](https://user-images.githubusercontent.com/59444569/183852138-c5ef55c0-1fce-40f9-9ad0-2db181b21654.png)

![image](https://user-images.githubusercontent.com/59444569/183852017-51c3fb70-8bd8-4506-aadf-9cd2612e3776.png)

</details>

This behaviour is observed in all tracks (side/main), except for those side tracks which are created from videos in `challenges` (algorithmic botany, coding in the cabana). It seems like the showcase cover images for videos outside `challenges` are not being loaded properly.

**Comment by shiffman** [comment]
Ah, thank @dipamsen! I didn't realize this was more than just the one 3.1 NOC video. @klinegareth and I will look into this. @fdoflorenzano if you have any ideas let us know!

**Comment by shiffman** [comment]
Thank you @fdoflorenzano! @kfahn22 after the site builds, go ahead and check video 3.1, we can re-open if there are still issues but should be working now!

**Comment by shiffman** [comment]
@kfahn22 alerted me to this particular showcase image which is not showing up (although 3.1 is indeed fixed!):

* https://github.com/CodingTrain/thecodingtrain.com/blob/main/content/videos/noc/3-angles/4-polar-coordinates/showcase/contribution3.png
* https://thecodingtrain.com/tracks/the-nature-of-code-2/noc/3-angles/4-polar-coordinates
 
<img width="501" alt="Screen Shot 2022-08-10 at 9 03 16 PM" src="https://user-images.githubusercontent.com/191758/184047967-aaf41cfa-21f8-4880-b414-b0c5c005855c.png">

Also, I'm not sure if this error was present before or if this fix re-introduced it, but the code example images are also missing from the tracks  now(challenges working properly).

* https://thecodingtrain.com/tracks/the-nature-of-code-2/noc/3-angles/1-angles-and-rotation

![image](https://user-images.githubusercontent.com/191758/184048122-6a130432-6fea-4552-9f3d-4b12872f1ba1.png)

Did I miss anything @kfahn22?

**Comment by kfahn22** [comment]
The code images were there in the preview yesterday.

**Comment by fdoflorenzano** [comment]
Hey! Another PR: https://github.com/CodingTrain/thecodingtrain.com/pull/442

> Also, I'm not sure if this error was present before or if this fix re-introduced it, but the code example images are also missing from the tracks now(challenges working properly).

This was introduced by the last update, the fix also affected the cover images for code examples. The PR should fix that.


> alerted me to this particular showcase image which is not showing up (although 3.1 is indeed fixed!):

This issue I'm not sure why, since when running locally it does appear for me. Maybe it's a cache thing? Clearing the cache may fix it?

**Comment by shiffman** [comment]
I think this is all working now! I forced clearing cache on the build:

https://thecodingtrain.com/tracks/the-nature-of-code-2/noc/3-angles/1-angles-and-rotation

<img width="950" alt="Screen Shot 2022-08-12 at 4 12 56 PM" src="https://user-images.githubusercontent.com/191758/184435627-d42540a4-00b0-4a90-92dc-7d46be3562c6.png">
