### ISSUE TITLE
Favicon is missing

### ISSUE THREAD

**Issue by DenisovichDev** [CodingTrain/thecodingtrain.com#444]
I have noticed that there is an absence of a favicon in the website. I'm not sure if there is a plan for that, but still I thought I should open this issue.

**Comment by shiffman** [comment]
@runemadsen I recall us discussing something for this? If you have an idea let us know!

**Comment by DenisovichDev** [comment]
I really love the semi colon character personally :)

**Comment by runemadsen** [comment]
Ah, good call! We can easily add one :) If everyone's okay with the semi colon character, we'll use that :)

**Comment by shiffman** [comment]
Works for me!
