### ISSUE TITLE
Code needed for video "16.14: async/await Part 2 - Topics of JavaScript/ES8"

### ISSUE THREAD

**Issue by 9opsec** [CodingTrain/thecodingtrain.com#455]
I'm looking for the async/await code associated with video linked below : 

https://www.youtube.com/watch?v=chavThlNz3s

I searched the Github repository for "wordGIF" and "wordnikAPI" but there were no results.

Thanks.

**Comment by dipamsen** [comment]
@9opsec This is the code associated with videos 16.13 - 16.15 (about Promises in JavaScript).
https://github.com/CodingTrain/website-archive/tree/main/Tutorials/P5JS/16_promises/13_16_async_await

**Comment by 9opsec** [comment]
> @9opsec This is the code associated with videos 16.13 - 16.15 (about Promises in JavaScript). https://github.com/CodingTrain/website-archive/tree/main/Tutorials/P5JS/16_promises/13_16_async_await

Thanks. That's what I was looking for.

**Comment by shiffman** [comment]
I'm going to leave this open as I'd love to get the code moved to its own repo and linked from a page on this site!

**Comment by dipamsen** [comment]
This code example has been [added here](https://editor.p5js.org/codingtrain/sketches/O-6gPkGeD).
The video page on the site is https://thecodingtrain.com/tracks/topics-in-native-javascript/js/async-await-part-2

**Comment by shiffman** [comment]
Thank you @dipamsen!
