### ISSUE TITLE
Filter links on track page broken

### ISSUE THREAD

**Issue by dipamsen** [CodingTrain/thecodingtrain.com#473]
![image](https://user-images.githubusercontent.com/59444569/185806176-bda1dce6-c6c7-44e7-b3b5-ba9454bdf27f.png)
These links lead to 404 pages.

**Comment by runemadsen** [comment]
This fix is a part of #456 and should be good once that PR is merged.

**Comment by shiffman** [comment]
@dipamsen can you check that this is ok and close if so?

**Comment by shiffman** [comment]
I just and this is working as expected! @dipamsen feel free to re-open if I'm missing something.
