### ISSUE TITLE
A Python Script to Port Contributions Easily

### ISSUE THREAD

**Issue by DenisovichDev** [CodingTrain/thecodingtrain.com#485]
I have made a tool to that makes porting the contributions easier! It's a python script that takes the old contribution metadata in markdown format as an input and creates individual `json` files containing the metadata of each individual contributions (following the new Gatsby format) that can now be copied into the `showcase` folder.

https://github.com/DenisovichDev/codingtrain-contribution-util

Information about how to use it and more could be found in the `README.md`. I hope this makes it easier for the contributors who are porting challanges.

**Comment by shiffman** [comment]
Hi @DenisovichDev this is wonderful, thank you for sharing! Tagging @kfahn22 and @dipamsen who have been doing a lot of the porting in case this is helpful. If you like you can add a note about this to the site maintenance guide (then we can close this issue). 

https://thecodingtrain.com/guides/maintain-website-guide

**Comment by DenisovichDev** [comment]
@shiffman I actually just found out about [skaser85/thecodingtrain_website_data](https://github.com/skaser85/thecodingtrain_website_data), because I had only read the content management guide from the README. The mentioned project does the job better than my script, so I'm not sure if I should add it. Wish I'd known about this beforehand. The main difference I'm seeing is that there is the `source` property in the templates which are no longer needed. And I guess if someone wants to do the porting more hands on, they can use this script.
Can you suggest me what you think I should do?

So sorry for the trouble.

**Comment by kfahn22** [comment]
@DenisovichDev I would have loved to have your script when I ported Coding in the Cabana and the ML track, so I think it is worthwhile adding.

**Comment by dipamsen** [comment]
@DenisovichDev The templates are only for coding challenges, so this script is still helpful for porting contributions from tracks. :)

**Comment by DenisovichDev** [comment]
Thanks @dipamsen and @kfahn22 for your feedback! I'll add it to the maintain-website-guide in appropriate places.

**Comment by shiffman** [comment]
Thanks everyone! @DenisovichDev feel free to close this issue once you've added what you feel is best!

**Comment by shiffman** [comment]
Thanks for adding!
