### ISSUE TITLE
Duplicate Languages Appearing in Dropdown

### ISSUE THREAD

**Issue by M0nica** [CodingTrain/thecodingtrain.com#488]
I noticed that there are duplicate languages appearing in the dropdown for different variations of the same language i.e, "processing" vs "Processing" and "p5js" vs. "p5.js"
<img width="716" alt="Screen Shot 2022-08-24 at 7 38 10 PM" src="https://user-images.githubusercontent.com/6998954/186542284-eb6a77f1-faa5-4f44-8630-5a9d9d31eb59.png">
<img width="705" alt="Screen Shot 2022-08-24 at 7 38 26 PM" src="https://user-images.githubusercontent.com/6998954/186542289-453a2707-1f2f-41f5-a466-7cbc5e2dcd5e.png">

This affects /tracks/lang/all/topic/all/ and /challenges. 

How do we want to normalize these languages so that there's one preferred way to refer to any given language?

**Comment by shiffman** [comment]
Thank you for working on this @M0nica! There is also #128 related to this. I've been meaning to get to this for a while now and do a big cleanup pass. We should probably establish some guidelines for these and add to the [site maintenance guide](https://thecodingtrain.com/guides/maintain-website-guide). Off the top of my head I would say all lowercase and no special characters? Thanks for reviving this discussion!

* p5js
* processing
* python
* basic
* etc

**Comment by shiffman** [comment]
I'm also fine with `p5.js` maybe that looks better!

**Comment by shiffman** [comment]
@allcontributors add @M0nica for code and content

**Comment by shiffman** [comment]
Thank you @M0nica, @dipamsen and @fturmel for all of your work on this! Closing this issue now that #799 is merged!
