### ISSUE TITLE
Showcase Page!

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#501]
I would love for the site to have a showcase page listing all of the submissions. . maybe with some sorting? Chronological? By author? Thoughts, ideas?

@runemadsen is this something DSI would like to help build or review or shall we press forward on our own?

Thank you!!

**Comment by runemadsen** [comment]
Excellent!

I think the act of implementing this will not be too crazy if you take the logic from the other pages and use the existing passenger showcase component:

<img width="404" alt="Screen Shot 2022-08-30 at 8 43 23 AM" src="https://user-images.githubusercontent.com/192021/187368034-8ba0cf5e-491a-4b2b-8e09-a324dabe7aec.png">

Do you have people on your end who could give it a try? We will of course be happy to do a thorough review.

A few things that I think will be involved in this task:

1. The current passenger showcase component has a fixed width, as it's used in a horizontal scroller. If used on a page, we probably want the component to be able to be fluid so it can take up 1/3 or 1/4 of the container width, like the other components on the listing pages. I suggest doing this by passing either a `className` to the component with styles that override the component styles of by doing a `variant` prop and adding the alternative style in the component itself.

2. Regarding filter, I would suggest having a single `sort`, so we don't need to generate combinations of filters and slow down the build process. I think sorting by newest submissions by default would be a great way to increase user contributions, and this could perhaps be the only sorting in the beginning and then the extra sorting could be added as a separate PR.

Happy to answer any questions you have about this!

**Comment by shiffman** [comment]
Great, thank you @runemadsen! I think we can take it from here and if we have questions or are ready for a design review, we'll tag you!

**Comment by kfahn22** [comment]
I have been thinking that it would be nice to have a place where student contributions are showcased, although I suppose that would complicate things.

**Comment by kfahn22** [comment]
I think it would be helpful to have a list of all the files that need to be updated or added  to add a Showcase Page.  I have come up with a list, but  I am not sure if it is correct.  Have I missed some files or included some  files by mistake?

gastby-node.js
gastby-config.js

In the node-scripts folder:
page-generation.js
node-generation.js
schema.js

pages/index.js

In the components folder, add:
ShowcasePanel.js
ShowcasePanel.module.css

**Comment by shiffman** [comment]
Thanks @kfahn22! @klinegareth is planning to work on this page so can provide more info and any requests in terms of help!

**Comment by shiffman** [comment]
Thank you to all the wonderful contributors who helped to make this page happen in #638, now merged! Closing this issue and opening a new one to discuss refinements.
