### ISSUE TITLE
Showcase "Submit" Button hover

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#511]
I noticed when testing that the showcase submit button does not change to a "hover" cursor which makes for a slightly confusing interaction. Would love any help fixing this!

https://thecodingtrain.com/guides/passenger-showcase-guide

<img width="925" alt="Screen Shot 2022-08-31 at 10 13 56 AM" src="https://user-images.githubusercontent.com/191758/187700209-2502d7b3-f24b-4d04-a3f0-9241fb6df68d.png">

**Comment by dipamsen** [comment]
Also, there should be some indicator to show that the entry is being submitted (eg. Button disabled state).

**Comment by zvolcsey** [comment]
Hey I added missing hover state in this pr. #545

**Comment by shiffman** [comment]
@allcontributors add @zvolcsey for code

Thank you @zvolcsey!!
