### ISSUE TITLE
Showcase Submission Enhancements

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#512]
Here is a list of "nice to have" but not critical enhancements to the showcase submission process. If anyone wants to take any of these on, just reply here!

* [x] Add `showcase` label automatically to pull request
* [x] Embed image into the pull request comment
* [ ] Create option for videos that are not coding challenges in the dropdown list (this might require some clever thinking given how many videos this would add.)

**Comment by dipamsen** [comment]
I am working on adding the showcase label and image preview.

**Comment by shiffman** [comment]
Thank you @dipamsen! I'll leave this open but we could also great a new issue for the third item if that is more convenient.

**Comment by fturmel** [comment]
I think we can close this issue, #1130 completed the last task!
