### ISSUE TITLE
Link to Nebula Video

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#524]
I'd like to add to the JSON data for each video a nebula property that links to the video on nebula (if it is there). For example:

https://youtu.be/7r83N3c2kPw -> https://nebula.tv/videos/codingtrain-coding-challenge-173-applesoft-basic-snake-game

I'd love to then incorporate this into YT description generator (cc @dipamsen). We could also add it to the page for each video as well.

**Comment by fturmel** [comment]
Working through adding the Nebula slugs to videos.

I extracted the titles and urls/slugs from the https://nebula.tv/codingtrain page (177 videos), and put them in this Google sheet to track progress: https://docs.google.com/spreadsheets/d/1-DpihoHjDcN2KEZufQBoxZ9zB-WblVjMzFIzYlFMGss/edit?usp=sharing

**Comment by fturmel** [comment]
@shiffman Between #950 and #952 this covers all Nebula video I think. If you can review the spreadsheet, there are a few clarifications needed to complete this data entry task.

- The p5.js code track chapter 2 seems to have dupes/mismatches between the Coding Train vids and Nebula. Was chapter 2 re-recorded at some point? (these are highlighted in spreadsheet in yellow and cyan)
- Are there missing tracks on the Coding Train site still? I saw Nebula videos for "Teachable Machine" and "Discord bots" tracks.
- Some misc videos (like ITP show and uncut versions) I supposed are Nebula exclusive. I flagged them but it's probably expected that there are no matches on the site.
- I couldn't find a good match on the site for the Nebula video "Working with Data and APIs in JavaScript".

That's about it!

**Comment by dipamsen** [comment]
> Are there missing tracks on the Coding Train site still? I saw Nebula videos for "Teachable Machine" and "Discord bots" tracks.
Quite a few... I think from the list in #279, the 'Learning Processing' videos are being remade, 'Discord Bots' and 'Twitter Bots' videos are pretty much outdated. The only one actually yet to be ported (from the list) is 'Guest Conductors'

**Comment by fturmel** [comment]
@dipamsen thank you for your insights here! I updated one of the PR and the spreadsheet based on them.

There is a video on Nebula about JS objects (coding-train-2-3-javascript-objects-p5-js-tutorial) that doesn't have a match. Was it simply replaced by the 2.3 video (incrementation) and should be flagged as outdated?

**Comment by shiffman** [comment]
Yes, this is an old video that I no longer include in the Code! track.

It would be great to have Teachable Machine as a track! I think all the "high priority" tracks are on the site and we can just add them whenever someone is inspired to or by request!

**Comment by fturmel** [comment]
What's next for this issue? Linking to the Nebula videos from Coding Train videos?

It seems like a few were manually added in the References tab. Is this where we want them for all videos?

<img width="1510" alt="Screenshot 2023-02-28 at 9 15 06 AM" src="https://user-images.githubusercontent.com/4009209/221879807-76ab503a-7700-44ce-9794-f8b2d8091c39.png">

**Comment by shiffman** [comment]
Thanks @fturmel! I think the two next steps are:

* Make any improvements to the yt-description generator script to include the Nebula link (I added something previously so it's probably fine but worth taking a look.)
* Add a link to the video on Nebula on the webpage.

For the second item, I'd love to feature it a bit more prominently than just one of many links under "references" but the site was not designed with this in mind so I'm not sure what is best. We could try, just as an experiment adding something like "watch this video ad-free on Nebula" with a link in the blank row between the embed and the tabs? We could also include the Nebula logo?

**Comment by dipamsen** [comment]
> Make any improvements to the yt-description generator script to include the Nebula link (I added something previously so it's probably fine but worth taking a look.)

This is how the descriptions are generated looks currently:

![image](https://user-images.githubusercontent.com/59444569/221939190-89bc54a4-e7e5-477c-862e-2a0e38088fab.png)

Is there any modification required?

**Comment by shiffman** [comment]
> Is there any modification required? (maybe a punctuation mark between the text and the link)

I think it's all good!

**Comment by fturmel** [comment]
@shiffman I think we can close this issue.

For future reference, here are the Nebula slugs for the two tracks that have yet to be integrated in the website:

**Teachable Machine**
the-coding-train-yt-teachable-machine-3-sound-classifiication
the-coding-train-yt-teachable-machine-2-snake-game
the-coding-train-yt-teachable-machine-1-image-classification

**Discord bots**
the-coding-train-yt-discord-bots-6-building-a-command-handler
the-coding-train-yt-discord-bots-5-posting-gifs
the-coding-train-yt-discord-bots-4-hiding-api-keys-with-env
the-coding-train-yt-discord-bots-3-coding-a-bot-with-discord-js
the-coding-train-yt-discord-bots-2-discord-developer-portal
the-coding-train-yt-discord-bots-1-introduction

**Comment by shiffman** [comment]
Thank you! I'll open a new issue to track!
