### ISSUE TITLE
Skip Netlify Preview Build for changes to README + .allcontributors?

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#530]
@allcontributorsbot add @shiffman for code

**Comment by shiffman** [comment]
@allcontributors add @shiffman for code

**Comment by shiffman** [comment]
Does anyone know if there is a way to tell Netlify not to bother with a build for changes to the README only?

**Comment by fturmel** [comment]
@shiffman Per https://docs.netlify.com/site-deploys/manage-deploys/#skip-a-deploy, you can add `[skip ci]` or `[skip netlify]` in commit messages to control the CI/CD behavior.

More interestingly though, you can configure a command in a root `netlify.toml` config that can determine if a build and deployment should trigger for any given commit.
https://www.netlify.com/blog/2020/04/27/ignore-unnecessary-builds-to-optimize-your-build-times/

Maybe we can ignore builds for `*.md` files and `.allcontributors` at the root of the project?

**Comment by M0nica** [comment]
I opened up a PR to address this issue but wasn't sure if we wanted to ignore `*.md` or explicitly `README.md`. So my current implementation is just for `README.md` and the allcontributors file https://github.com/CodingTrain/thecodingtrain.com/pull/830

> @shiffman Per https://docs.netlify.com/site-deploys/manage-deploys/#skip-a-deploy, you can add `[skip ci]` or `[skip netlify]` in commit messages to control the CI/CD behavior.
> 
> More interestingly though, you can configure a command in a root `netlify.toml` config that can determine if a build and deployment should trigger for any given commit. https://www.netlify.com/blog/2020/04/27/ignore-unnecessary-builds-to-optimize-your-build-times/
> 
> Maybe we can ignore builds for `*.md` files and `.allcontributors` at the root of the project?

**Comment by shiffman** [comment]
Thank you! @M0nica and @fturmel, super appreciate your work on this and helpful explanation / documentation! I think we probably could do all `*.md` files too! I'm going to close this, yay!
