### ISSUE TITLE
Licenses on projects shared via p5js sketches

### ISSUE THREAD

**Issue by alin256** [CodingTrain/thecodingtrain.com#574]
@shiffman, I did not find the license for the projects linked via sketches rather than on GitHub.
E.g., https://thecodingtrain.com/challenges/124-flocking-simulation

Would it be a good idea to include it as part of the Coding Train website?

**Comment by shiffman** [comment]
Yes! Would you mind filing an issue here for discussion? Or let me know if you prefer I do! Maybe we can put something in the footer. 

https://github.com/CodingTrain/thecodingtrain.com

**Comment by alin256** [comment]
> Would you mind filing an issue here for discussion?

Isn't it here now?

**Comment by shiffman** [comment]
LOL oooooops, for whatever reason I thought I was in the HDD repo, I was confused! Let me remove this thread and reply correctly!

**Comment by shiffman** [comment]
Yes, great idea! Maybe the footer would be a good place? Or perhaps it makes more sense to add a note to the README of the REPO given that the contents of the website itself would be under a different license. (Creative Commons Non Commercial probably).

**Comment by alin256** [comment]
I tried something, but I do not have a compiler setup. Take the pull request as a suggestion only. It might be arbitrary dysfunctional, and ugly.

**Comment by shiffman** [comment]
Thank you @alin256! It's my intention to use the same license for all of the code examples across the board so I don't think I need to add an additional data field to the build system. I think I can just put a note in the footer or in the GitHub README. I appreciate you thinking of this and helping propose ideas! @allcontributors add @alin256 for ideas and docs.

**Comment by shiffman** [comment]
@allcontributors add @alin256 for ideas and doc

**Comment by alin256** [comment]
> @allcontributors add @alin256 for ideas and doc

That is so cool :)

**Comment by shiffman** [comment]
Ah, I had an idea. I think I should add info to the README of the repo and also explain the licensing in the FAQ. @runemadsen is there any license requirements I should be aware of in terms of the website codebase itself? It's my intention that the Coding Train design assets (@jasontheillustrator's illustrations etc) are creative commons non-commercial but I don't know that I've ever explicitly specified that.

**Comment by runemadsen** [comment]
I think Gatsby is `The MIT License (MIT)` and so is all of the package dependencies. That's the only thing to be aware of as far as I know.

**Comment by shiffman** [comment]
I was just about to close this issue, but maybe I'll leave it open as it might be worth adding a note to the website FAQ?

https://thecodingtrain.com/faq

**Comment by shiffman** [comment]
I never got around to adding it to the FAQ but I think it's good enough to have in the README for now. If anyone wants to add to FAQ go for it!
