### ISSUE TITLE
More randomized content

### ISSUE THREAD

**Issue by lobertrand** [CodingTrain/thecodingtrain.com#590]
Choo choo! We recently introduced randomized content on the website in the "Try a challenge!" section (on the challenge and track video page) (PR #572). Here are some other places where randomized content could make sense :

## Featured challenges on the Homepage

Currently, there can be **any number** of featured challenges and they are laid out in rows of 3 :

![featured_challenges](https://user-images.githubusercontent.com/37326143/192112316-0350187d-b2d4-41d4-9f7b-c7d641d06f03.png)

Here is the corresponding configuration ([`content/pages/homepage/index.json`](content/pages/homepage/index.json)) :
```json
  "challenges": {
    "title": "Challenges",
    "description": "...",
    "featured": [
      "174-graphics-applesoft-basic",
      "171-wave-function-collapse",
      "166-image-to-ascii",
      "126-toothpicks",
      "162-self-avoiding-walk"
    ],
    "challengesCta": {...}
  },
```

We could limit the number of challenges that are shown (to 3 or 6 for example) and pick random ones from the "featured" array.

## Featured showcase on the Homepage

Currently, there is only one featured showcase one the homepage and it changes only if we change it manually and rebuild the website :

![featured_showcase](https://user-images.githubusercontent.com/37326143/192112324-c30bb0c8-da07-492f-be70-853204bf783a.png)

Here is the configuration ([`content/pages/homepage/index.json`](content/pages/homepage/index.json)) :
```json
  "passengerShowcase": {
    "title": "Passenger showcase highlight",
    "featured": "challenges/173-snake-applesoft-basic/showcase/contribution-1661456933.json",
    "cta": {...}
  },
```
If we want to be able to pick a random contribution from a list of options, we could transform the `featured` property into an array :
```json
  "passengerShowcase": {
    "title": "Passenger showcase highlight",
    "featured": [
      "challenges/173-snake-applesoft-basic/showcase/contribution-1661456933.json",
      "challenges/102-2d-water-ripple/showcase/contribution3.json",
      "code/3-conditionals/1-conditionals/showcase/contribution3.json"
    ]
    "cta": {...}
  },
```

## Scrollable passenger showcase on the Challenge and Track video page

Currently, the items of the passenger showcase on the challenge and track video page appear in alphanumerical order of their JSON filename :

![passenger_showcase](https://user-images.githubusercontent.com/37326143/192112337-c479ab28-fa00-4bd3-9a2c-5c5550b207d5.png)

We could shuffle them on every page refresh, to give them all an equal chance to be seen.

In all cases, we should keep in mind what @runemadsen said on PR #572 :
> I'm all for choosing a random challenge on the client side if we can stay under a length of 30 challenges. Since we need to load all the challenges on the client and only show one random one, it's adding kb to the page, but as long as we don't go wild, I think it's perfectly fine.

**Comment by shiffman** [comment]
Hi @lobertrand, excited to try adding some more randomizers, yes! Here are some thoughts, let me know if I missed responding to anything important or if you have more questions!

### Challenges on Homepage

> We could limit the number of challenges that are shown (to 3 or 6 for example) and pick random ones from the "featured" array.

I think the homepage looks nice with 3 challenges. Let's start with a list of 3 or more and randomly show 3 each time!

### Passenger Showcase on Homepage

> If we want to be able to pick a random contribution from a list of options, we could transform the featured property into an array.

Yes, this is a great solution! Part of me wonders if we should show more than 1 showcase projects, but that would involve adjusting the design. So perhaps we start with highlighting 1 picked at random from a list of N projects. But if you want to try showing 3 like with the challenges I'm open to that too!

### Showcase on Video Page

> We could shuffle them on every page refresh, to give them all an equal chance to be seen.

Yes, I think that would be great!

**Comment by lobertrand** [comment]
I'm gonna work on the Passenger Showcase on Video Page first :smiley:

**Comment by shiffman** [comment]
I think these are all completed and this can be closed! Let me know @lobertrand, thank you again for the tremendous work on this feature!

**Comment by lobertrand** [comment]
> I think these are all completed and this can be closed! Let me know @lobertrand, thank you again for the tremendous work on this feature!

Yes, we can close this one! It's a pleasure to be able to contribute to this 😁
