### ISSUE TITLE
Hacktoberfest 2022 Preparations

### ISSUE THREAD

**Issue by DenisovichDev** [CodingTrain/thecodingtrain.com#611]
It's time for hacktoberfest again. And I think like the last website repository, we should use this event to attract more people to contribute! Now I know there is the chance of potential spam PRs (like every time), but this year they have made the rules much more strict for the mess last year. So personally I think the `hacktoberfest` topic, and probably some other topics (since there aren't any as of now), should be added to the repo. What do you think?

**Comment by shiffman** [comment]
Yes, I would love to participate! Let me know what you think I should do to get things organized and ready. If you would like to help I'd be glad to add you to the repo!

**Comment by AyushKoul00** [comment]
I recently added my submission to one of the coding challenges in this repo (as a json file) and created a PR. However, this repo is not recognized as a repo that is participating in Hacktoberfest. Will this change in the near future?

**Comment by DenisovichDev** [comment]
@shiffman Yes, I am definitely up for that, I would love to help!

This is what I think should be done to get things cleaned up and organized (some of these are optional):
- [ ] Firstly, adding the `hacktoberfest` topic to the repo, along with a few other ones (like the archived repo).
- [ ] Closing issues that are old and could be closed by now. Since a lot of new people are going to actively try to contribute, it is something that could be kept in mind.
- [ ] Labelling issues that you think could be something the hacktoberfest contributors can work on with the `hacktoberfest` label.
- [ ] Having an issue for the coding challenge and video ports. This issue would be labelled with `hacktoberfest`, and there would be links to the `maintain-website-guide` page, as well as the spreadsheet. Why? Because new contributors coming from hacktoberfest would look for contributions that they can give, and the issue makes it easier for them. And this issue should be mentioned in every porting PR, to keep track of things. I think it is cleaner this way.
- [ ] It should be mentioned in `README` or `CONTRIBUTING.md` that spam PRs are not welcome, and they will not be merged.

I'd like to hear your thoughts on this, as well as other maintainers'. Please feel free to tell me if you don't agree with some of these, or if you would like to add somethings.

**Comment by DenisovichDev** [comment]
@AyushKoul00 hopefully, we are trying to get things organized.

**Comment by shiffman** [comment]
Tagging @klinegareth @dipamsen and @kfahn22 for their thoughts as well!  I can work on adding the `hacktoberfest` topic, label, and closing old issues. I'll need help with cleaning up the about section, README, CONTRIBUTING, and opening an new issues we want to specifically note as part of hacktoberfest.

**Comment by DenisovichDev** [comment]
@shiffman I can help with that!

**Comment by kfahn22** [comment]
I have a couple of questions.  Some of the participants have officially registered and are listed on the Hackobefest site.  I am assuming this is optional, but I am wondering if CT should register (many--but not all--of  registered participants have swag for  a specified number of verified pull requests).  @DenisovichDev are you working on a CONTRIBUTING.md file?

**Comment by shiffman** [comment]
I'm open to registering and offering stickers etc! Maybe we could even make a CT hacktoberfest specific one? cc @jasontheillustrator

**Comment by DenisovichDev** [comment]
@kfahn22 not right now since I was waiting for some more output about this from other maintainers, but I certainly can start, if you want me to

**Comment by shiffman** [comment]
I am creating a hacktoberfest team and adding permissions to this repo so you can help manage labels, etc!

**Comment by kfahn22** [comment]
Here is the link to register.  https://hacktoberfest-swag.com/CONTRIBUTING.html#participant-file
 @DenisovichDev I can help with the CONTRIBUTING.md file if you would like.

**Comment by DenisovichDev** [comment]
@kfahn22 Yeah I'm definitely gonna need help, thanks!

**Comment by kfahn22** [comment]
Should Hacktoberfest be listing in Events on the Homepage?

**Comment by shiffman** [comment]
> Should Hacktoberfest be listing in Events on the Homepage?

I'm open to that! I've done a terrible job of keeping the events updated, I wonder if I should deprecate this section. Certainly we can try it for hacktoberfest.

I should probably add this event!
https://caveat.nyc/events/aeoud-10-8-2022

**Comment by DenisovichDev** [comment]
@shiffman  Should I add a temporary note in the `README` to check out `CONTRIBUTING` for `hacktoberfest` related info?

**Comment by shiffman** [comment]
Sure! Good idea!

**Comment by kfahn22** [comment]
Based on a comment from @dipamsen that the showcase submissions made through the website don't need the hacktoberfest label  (which makes perfect sense, now that I think of it) I am wondering how contirbutors  get credit for the pull request.  Is it based on email or GitHub user name?

**Comment by DenisovichDev** [comment]
@kfahn22 They have to authorize hacktoberfest to be linked to their GitHub/GitLab. That's how they keep track, I think

**Comment by kfahn22** [comment]
Yes,  I signed up to see what the process entailed and that is what happened.  I am wondering if we need to clarify that showcase contributors that want credit for Hacktoberfest should submit a pull request through their GitHub account?

**Comment by DenisovichDev** [comment]
Yeah I think so, the form submission wouldn't work. But I think people who are coming from hacktoberfest would know that they have to do a pull request from their account for it to be recognised. But still no harm to mention that in `CONTRIBUTING.md`

**Comment by DenisovichDev** [comment]
Also, It probably should be mentioned that spam PRs are not welcome.
