### ISSUE TITLE
Update Passenger Showcase Guide

### ISSUE THREAD

**Issue by dipamsen** [CodingTrain/thecodingtrain.com#628]
Passenger Showcase Guide: https://thecodingtrain.com/guides/passenger-showcase-guide

![image](https://user-images.githubusercontent.com/59444569/194218341-811ffbff-c260-4334-9d8f-7df684252ab9.png)

I believe this is not actually an option for non maintainers, they have to fork the repo before creating a branch in it. This additional step should be mentioned in the guide.

**Comment by shiffman** [comment]
A very late reply, thank you @kvashchuka for updating the guide! 

@allcontributors please add @kvashchuka for documentation
