### ISSUE TITLE
Video JSON credits <-> YT description generator

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#771]
The description generator adds default credits for each video but I sometimes have extra ones (like for the Apple ][ video). One option would be to create a "credits" groupLink, but maybe we can add a separate credits property to each JSON instead?  RIght now I'm manually editing the YT descriptions:

<img width="629" alt="Screen Shot 2022-11-12 at 11 56 24 AM" src="https://user-images.githubusercontent.com/191758/201485511-87e0fd0a-fe83-4b9a-86d2-0627f1cc7dc5.png">

What do you think @dipamsen?

**Comment by dipamsen** [comment]
This would depend on whether we would like to show the credits on the website, and either solution would work for `yt-desc` (maybe a separate property would be a bit better for customisation)

**Comment by shiffman** [comment]
I think a separate property is best! I might propose:

```json
   "credits":[
      {
         "title":"What They Did",
         "name":"Name or Nickname",
         "url":"optional URL"
      },
      {
         "title":"Coding Together Theme",
         "name":"Will from America",
         "url":"https://twitter.com/WillfromAmerica"
      }
   ]
```

Perhaps we try adding these for the three Apple II videos and see how it feels / works?

**Comment by shiffman** [comment]
They could populate the YT description as well as create either a tab on the website or maybe just be listed at the bottom of the description for each video?

**Comment by dipamsen** [comment]
I think adding it below the description could be a good idea. I will try adding this.

**Comment by dipamsen** [comment]
I was playing around with this, and this is the behaviour I could achieve:

```jsonc
  "credits": [
    {
      "title": "Coding Together Theme",
      "name": "Will from America",
      "url": "https://twitter.com/WillfromAmerica"
    },
    {
      "title": "Eye of the Tiger cover",
      "name": "Leon from @neo"
    }
  ]
```

![image](https://user-images.githubusercontent.com/59444569/201509158-a36234d8-3d11-41b6-88ea-82ee540936e5.png)

1. Now that the description is a bunch of elements instead of a string of text, the Read More / Read Less doesn't work, and the section has become scrollable. I am not sure how easy or difficult it would be to re-implement that behaviour here.
2. Here, `Will from America` links to the url (currently invisible due to lack of styling).
3. Currently I have implemented this with a bunch of `<br />` tags, which is probably not the best for accessibility. Open for suggestions!

Here is the rendered HTML: 
![image](https://user-images.githubusercontent.com/59444569/201509452-cc731254-8e96-45ef-9f84-601701753c38.png)

**Comment by shiffman** [comment]
This is a good start! A few thoughts.

1. Should it be a separate tab or inside the description? I could go either way.
2. If it's in the description I think we need the "read more" to work so that it doesn't overflow awkwardly.
3. The credits should also include video editing and animation. These are now automatically added for all videos. Does it make sense to include them additionally in the JSON? It would be extra work to do so but that might make the most sense in order to be able to fully customize the credits?

I'll have to think about this some more. Open to feedback!

**Comment by dipamsen** [comment]
@shiffman Appreciate the input! 

I tried both using the description or creating a new tab, to see which works well with the site.

## A. Below the description
The way the `Read More / Read Less` system works on the size is that it requires the content of the description to be a string, as the collapsing of the description depends on the character length of the content. However, on adding the credits, it adds a bunch of `<br>` and `<a>` attributes, so this functionality breaks.

This is the output I could get: (better pic in above comment)
![v1_scroll](https://user-images.githubusercontent.com/59444569/202267960-ab9ba971-4b64-4864-a5d0-6558b6db5df8.png)

While experimenting, I found that it could work, if we decided not to use `urls`:

https://user-images.githubusercontent.com/59444569/202268961-17a78071-986d-4d7d-b17e-0f97018e3e25.mp4

I cannot think of an elegant way that this can be done, while preserving the current collapsible system. If anyone can suggest something, I could try implementing it!

## B. A new tab

I used most of the code from `LinkList` (aka `groupLinks`) and created a `CreditList` component.

![v2_tabs](https://user-images.githubusercontent.com/59444569/202269258-8fe59692-1d1a-4d97-8743-60c3f4fb4dcb.png)

I am not the best at designing, but I tried to create a layout matching the other tabs.

-----

1. > The credits should also include video editing and animation. These are now automatically added for all videos. Does it make sense to include them additionally in the JSON?
   Sure! I'll add them to all challenges, once it is implemented.

2. Note that `Additional Music from Epidemic Sounds` has changed into `Additional Music by Epidemic Sounds`. I do not know how this can be dealed with, I have decided to use `by` as the default as it works with most entries.

Should I keep working on the new tab layout, or is the credits below description worth revisiting? Any feedback is appreciated!

P.S. Deploy Preview for the tab layout: https://deploy-preview-775--codingtrain.netlify.app/challenges/174-graphics-applesoft-basic

**Comment by dipamsen** [comment]
Just realised that this just adds yet another extra tab 😕

![image](https://user-images.githubusercontent.com/59444569/202835637-280445da-8b94-4b09-8821-7704b1fb873e.png)

**Comment by shiffman** [comment]
Thank you so much for working on this! I'm worried I'm overcomplicating things by adding this feature, then again it is very important to credit people for their hard work on the videos! @kfahn22 Do you have an opinion here having worked on so many of these JSON files? Is it going to be a pain to maintain the credits this way? I think the Apple video is unusual with so many tabs so adding a credits one probably won't be an issue for most.

**Comment by shiffman** [comment]
This is settled with #775!
