### ISSUE TITLE
copy link button confirmation not visible when pushed to next line

### ISSUE THREAD

**Issue by dipamsen** [CodingTrain/thecodingtrain.com#772]
![image](https://user-images.githubusercontent.com/59444569/201487483-41906447-1af6-4d6e-babd-43fbbcd570a7.png)

When there are a lot of `groupLinks` entries, the additional entries overflows out of the screen instead of wrapping / scrolling.

Example: https://thecodingtrain.com/challenges/175-3D-cube-applesoft-basic

**Comment by shiffman** [comment]
@kfahn22 and I were discussing this. I think maybe it's best for me to limit myself to 6 grouplinks max? For this one we can combine AppleSoft BASIC and Apple II Emulators. Maybe there's a more succinct way to say "unedited raw footage" as well.

**Comment by kfahn22** [comment]
I think "raw" implies unedited.

**Comment by dipamsen** [comment]
I guess we could technically add a horizontal scroll for this, but I'm not sure if it is good for the overall accessibility and design.

**Comment by dipamsen** [comment]
Another point to note is, for the "Copy Link" button when wraps to the next line (which is the case for most recent challenges), on clicking on the button, the confirmation text "Copied Link!" appears on the left of the button, which is almost completely out of the screen.

**Comment by shiffman** [comment]
I think it's good to just limit the number of tabs and length of text so it's not worth engineering a scroll. However, while low priority, it might be nice to fix the copy link button issue when the tabs push it to the next line.

Changed the title to reflect this new issue.

<img width="336" alt="Screen Shot 2022-11-14 at 10 29 33 AM" src="https://user-images.githubusercontent.com/191758/201699708-5315e929-0cd7-4916-a71f-77a161c7b425.png">

**Comment by laurie60** [comment]
I think I fixed this issue, this is my first time contributing to an open source project!

**Comment by laurie60** [comment]
Hello! I just realised that the my fix that was merged is not working unless the window is resized, so if you start off with a window size that gives you two lines, the alert still pops off screen. 

I have implemented a fix (to my fix!) by adding a useEffect that runs on the pages first rendering in another pull request #812.

I have tested it a lot now, using Chrome and Safari, and it works on my local build. Most of the time...

There is one situation where it still seems to fail though-which is on chrome where you navigate directly to a challenge video page. Where the alert should go to the right, it still goes to the left.  It does work on chrome when you navigate to the same page from another screen, and it also seems to work on Safari in all circumstances. I'm not sure why this is 🤔.

**Comment by shiffman** [comment]
Thank you @dipamsen for reporting this and @laurie60 for fixing! I'm going to close this now as I think it's working great! It's ok with me if it's a little buggy, it's rare this issue comes up. If you notice anything else please re-open this issue or a new one! 🚀
