### ISSUE TITLE
Group Link titles cut off on smaller screen sizes

### ISSUE THREAD

**Issue by dipamsen** [CodingTrain/thecodingtrain.com#798]
In small screens, longer titles which wrap around on multiple lines are not visible properly.

![image](https://user-images.githubusercontent.com/59444569/204095932-2008f7cb-5403-4265-aec8-96bad5998161.png)

**Comment by M0nica** [comment]
It looks like this is a screenshot of looking at the references links at https://thecodingtrain.com/challenges/171-wave-function-collapse on smaller screens. I was able to reproduce this issue. Pasting the link here to provide more context on this issue.
