### ISSUE TITLE
Archive page?

### ISSUE THREAD

**Issue by fdoflorenzano** [CodingTrain/thecodingtrain.com#81]
We've been wondering if a archived tracks page would also be needed, as the [existing site has](https://thecodingtrain.com/more/archive/). 

@bravomartin and I talked about how it could be easy to add. Maybe by having new boolean property in track files that label them as "archived", and that moves them from the `/tracks` page to new `/archive` one. The base for this new `/archive`  page could be similar to `/tracks`, but with enough visual differences that show that this is outdated content. Through sizing and maybe color?

**Comment by shiffman** [comment]
To keep things clean and organized I think I will close this page, there has not been a need yet to archive anything and for now we can use tracks for this purpose. Happy to re-open if anyone wants to discuss further or work on implementing this!
