### ISSUE TITLE
Cleanup dead GitHub branches

### ISSUE THREAD

**Issue by fturmel** [CodingTrain/thecodingtrain.com#910]
I posted this on Discord yesterday, but it probably makes sense to leave it here too.

> I just noticed there are 477 branches in the repo... might be a good idea to clean that up eventually and check the repo setting to automatically delete merged branches. https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches

**Comment by shiffman** [comment]
I have added this setting! I also added the following, I hope it doesn't create a lot of noise in passenger submissons, but I do think this is something helpful to have especially for new site features like #501 etc.

<img width="828" alt="Screen Shot 2023-01-30 at 10 40 53 AM" src="https://user-images.githubusercontent.com/191758/215523120-13ef3e3b-5d2f-447c-9480-f862e09b6215.png">

I'll leave this open and will revisit later when I have time to do the cleanup.

**Comment by fturmel** [comment]
@shiffman Took the liberty to clear out some obvious closed/merged showcase-related branches. We're down to 153.

**Comment by shiffman** [comment]
Amazing, thank you!! Shall we leave this open for a bit as a reminder?

**Comment by fturmel** [comment]
Leave it open. I can do more cleanup, but I think you'll have to probably finish the job. Some branches are stale without PRs so I have no idea if they have valuable content in them.

Some examples:

![image](https://user-images.githubusercontent.com/4009209/217566283-699344cb-f920-4393-8cbe-c30ce978b249.png)

**Comment by fturmel** [comment]
OK, only 40 left. @shiffman if you want to finish reviewing the ones that do not have an "open" or "draft" status we can then close this issue.

https://github.com/CodingTrain/thecodingtrain.com/branches/all?page=1
