### ISSUE TITLE
Consider adding Teachable Machine and Discord Bot side tracks

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#965]
Picking up from #524, @fturmel noticed that these videos (on Nebula) are missing from the website.

The teachable machine videos are still relevant so they should be included but I could go either way on the Discord bot ones since those are pretty out of date (hopefully I'll make new ones sometime in the not too distant future!)

**Teachable Machine**
the-coding-train-yt-teachable-machine-3-sound-classifiication
the-coding-train-yt-teachable-machine-2-snake-game
the-coding-train-yt-teachable-machine-1-image-classification

**Discord bots**
the-coding-train-yt-discord-bots-6-building-a-command-handler
the-coding-train-yt-discord-bots-5-posting-gifs
the-coding-train-yt-discord-bots-4-hiding-api-keys-with-env
the-coding-train-yt-discord-bots-3-coding-a-bot-with-discord-js
the-coding-train-yt-discord-bots-2-discord-developer-portal
the-coding-train-yt-discord-bots-1-introduction

**Comment by SilvestriStefano** [comment]
Hello,
I can take on adding the Teachable Machine side track, if it is ok.

**Comment by shiffman** [comment]
Apologies @SilvestriStefano, I know I suggested this in the first place here and now I'm wondering whether Discord Bot should be included!!

**Comment by SilvestriStefano** [comment]
No worries!
Question: are you planning to replace the videos, or to add new ones and also keep these?

**Comment by shiffman** [comment]
@SilvestriStefano my plan (which will likely happen this fall though ideally sooner) is to replace the videos. The old ones will remain archived on YouTube but would not live on the CT website.

**Comment by shiffman** [comment]
I think this can now be closed, new discord bot videos are on the site as well as the TM videos!
