### ISSUE TITLE
p5.js transformations side track

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#982]
I'm rewriting Chapter 8 of the nature of code which includes the following, would be great to link to a side track on the website for the transformation videos!

> The part that is a bit more difficult than the previous fractals lies in the use of the word *rotate* in the fractal’s rules. Each new branch must rotate relative to the previous branch, which is rotated relative to all its previous branches. Luckily for me, p5.js has a mechanism to keep track of rotations—***transformations***. 
>
> Transformations refer to a set of functions, such as `translate()`, `rotate()`, `scale()`, `push()`, and `pop()`, that allow you to change the position, orientation, and scale of shapes in your sketch. The `translate()` function moves the coordinate system, `rotate()` rotates it, and `push()` and `pop()` help save and restore the current “transformation state.”
>
> If you aren’t familiar with these functions, I would suggest [[Gene Kogan’s p5.js Transformations tutorial](https://genekogan.com/code/p5js-transformations/)](https://genekogan.com/code/p5js-transformations/) or [my transformations in p5 video series](https://youtu.be/o9sgjuh-CBM), which covers the concepts in more detail.

**Comment by dipamsen** [comment]
The videos on Youtube are named as:
- Part 1: translate(), rotate(), push() and pop()
- Part 2: scale()
- Part 3

Description for Part 3:
> In this video, I look a bit behind the scenes on how transformations work and where the terms "push" and "pop" come from.  I discuss the difference between a stack and a queue, rotate() vs rotateZ(), and what a "matrix" refers to in computer graphics. 

What is a good title for part 3?

**Comment by shiffman** [comment]
hmmmm, this is a tough one! Some ideas:

* Part 3: More about push() and pop()
* Part 3: How do transformations work?
* Part 3: More about Transformations
* Part 3: Behind the scenes of Transformations
* Part 3: Stacks, Queues, 3D, and the Matrix

What do you think?

**Comment by dipamsen** [comment]
I think "More about Transformations" works the best.

**Comment by dipamsen** [comment]
Looks like the code examples of these videos are not available, I'll have to recreate them. Should I add them in the p5.js web editor?

**Comment by dipamsen** [comment]
Looks like the code examples of these videos are not available, I'll have to recreate them. Should I add them in the p5.js web editor?

**Comment by shiffman** [comment]
> Looks like the code examples of these videos are not available, I'll have to recreate them. Should I add them in the p5.js web editor?

That would be amazingly helpful! Do you have access to the Coding Train editor account? (we can coordinate over DM on Discord)
