### ISSUE TITLE
Genetic Algorithms Side Track or NOC track?

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/thecodingtrain.com#984]
Approaching the Nature of Code chapter 9 and wondering if we should bring the GA videos to a side track and/or maybe the NOC track?

https://www.youtube.com/playlist?list=PLRqwX-V7Uu6bJM3VgzjNV5YxVxUwzALHV

**Comment by dipamsen** [comment]
I think these videos can be placed in a side track for now, and later can be incorporated to NOC when its videos are done?

**Comment by shiffman** [comment]
@dipamsen I think I would consider this set of GA videos as "completed" (though I could imagine adding more in the future).

**Comment by dipamsen** [comment]
@shiffman sorry, I meant that GA is chapter 9, but in the site videos are present till chapter 5 only, so the GA should be added to the noc track once the remaining NoC videos are done

**Comment by shiffman** [comment]
That's a good point. I think one issue is that I may not create videos for chapters 7-8 other than the challenges (since fractals and CAs fit so well into the Coding Challenges). I intend to do a new one for Wolfram CA 1D soon, but otherwise maybe we should collect the most relevant challenges into the track?

**Comment by kfahn22** [comment]
Where does this stand?  Is anyone working on this?

**Comment by dipamsen** [comment]
@kfahn22 I was going to work on it, but if you want to, go ahead!

**Comment by kfahn22** [comment]
@dipamsen  Thanks, I could also start adding  Box2D videos, but that is less of a priority.  I have some time now, so if you haven't already started I could work on this.

**Comment by dipamsen** [comment]
> @dipamsen  Thanks, I could also start adding  Box2D videos, but that is less of a priority.  I have some time now, so if you haven't already started I could work on this.

For sure!

**Comment by dipamsen** [comment]
I believe this has been added and can now be closed.

**Comment by fturmel** [comment]
Agreed, I think #1047 should've closed this issue

**Comment by shiffman** [comment]
Indeed, thanks for helping track these down!
